#include "sysdep.h"
#include "opcode/riscv.h"
#include <stdio.h>


const char riscv_fpr_names_abi[NFPR][NRC] = 
 {
	"ft0", "ft1", "ft2", "ft3", "ft4", "ft5", "ft6", "ft7", 
"fs0", "fs1", "fa0", "fa1", "fa2", "fa3", "fa4", "fa5", 
"fa6", "fa7", "fs2", "fs3", "fs4", "fs5", "fs6", "fs7", 
"fs8", "fs9", "fs10", "fs11", "ft8", "ft9", "ft10", "ft11"
};

const char riscv_fpr_names_numeric[NFPR][NRC] = 
 {
	"f0", "f1", "f2", "f3", "f4", "f5", "f6", "f7", 
"f8", "f9", "f10", "f11", "f12", "f13", "f14", "f15", 
"f16", "f17", "f18", "f19", "f20", "f21", "f22", "f23", 
"f24", "f25", "f26", "f27", "f28", "f29", "f30", "f31"
};

const char * const riscv_vlmul[8] = 
 {
	NULL, "mf8", "mf4", "mf2", "m1", "m2", "m4", "m8"
};

const char * const riscv_vma[2] = 
 {
	"ma", "mu"
};

const char * const riscv_vta[2] = 
 {
	"ta", "tu"
};

const char riscv_vecm_names_numeric[NVECM][NRC] = 
 {
	"v0.t"
};


const char riscv_gpr_names_abi[NGPR][NRC] = 
 {
	"zero", "ra", "sp", "gp", "tp", "t0", "t1", "t2", 
"fp", "s1", "a0", "a1", "a2", "a3", "a4", "a5", 
"a6", "a7", "s2", "s3", "s4", "s5", "s6", "s7", 
"s8", "s9", "s10", "s11", "t3", "t4", "t5", "t6"
};

const char riscv_gpr_names_numeric[NGPR][NRC] = 
 {
	"x0", "x1", "x2", "x3", "x4", "x5", "x6", "x7", 
"x8", "x9", "x10", "x11", "x12", "x13", "x14", "x15", 
"x16", "x17", "x18", "x19", "x20", "x21", "x22", "x23", 
"x24", "x25", "x26", "x27", "x28", "x29", "x30", "x31"

};

const char * const riscv_vsew[8] = 
 {
	"e8", "e16", "e32", "e64", NULL, NULL, NULL, NULL
};

const char riscv_vecr_names_numeric[NVECR][NRC] = 
 {
	"v0", "v1", "v2", "v3", "v4", "v5", "v6", "v7", 
"v8", "v9", "v10", "v11", "v12", "v13", "v14", "v15", 
"v16", "v17", "v18", "v19", "v20", "v21", "v22", "v23", 
"v24", "v25", "v26", "v27", "v28", "v29", "v30", "v31"
};


const char * const riscv_rm[8] = 
{
};

const char * const riscv_pred_succ[16] = 
{
};

const char * const riscv_th_vediv[4] = 
{
};

const char * const riscv_fli_symval[32] = 
{
};

const float riscv_fli_numval[32] = 
{
};
const char * const riscv_th_vlen[4] =
{
};

#define MASK_RS1 (OP_MASK_RS1 << OP_SH_RS1 )
#define MASK_RS2 (OP_MASK_RS2 << OP_SH_RS2 )
#define MASK_RD (OP_MASK_RD << OP_SH_RD )
#define MASK_RM (OP_MASK_RM << OP_SH_RM )
#define MASK_PRED (OP_MASK_PRED << OP_SH_PRED )
#define MASK_SUCC (OP_MASK_SUCC << OP_SH_SUCC )
#define MASK_AQ (OP_MASK_AQ << OP_SH_AQ )
#define MASK_RL (OP_MASK_RL << OP_SH_RL )
#define MASK_AQRL (MASK_AQ | MASK_RL)
#define MASK_IMM ENCODE_ITYPE_IMM (-1U)
#define MATCH_SHAMT_REV8_64 (0b111000 << OP_SH_SHAMT)
#define MATCH_SHAMT_ORC_B (0b00111 << OP_SH_SHAMT)
##define MATCH_SHAMT_ZIP_32 (0b1111 << OP_SH_SHAMT)
#define MATCH_SHAMT_BREV8 (0b00111 << OP_SH_SHAMT)

static int 
match_opcode (const struct riscv_opcode *op, insn_t insn)
{
  return ((insn ^ op->match) & op->mask) == 0;
}

static int
match_rd_nonzero (const struct riscv_opcode *op, insn_t insn)
{
  return (op->pinfo == INSN_MACRO || match_opcode (op, insn))
	&& ((insn & MASK_RD) != 0);
}

const struct riscv_opcode riscv_opcodes[] =
{
{"add", 	0, INSN_CLASS_I, "d,s,t", 	MATCH_ADD, MASK_ADD, match_opcode, 0},
 {"add.uw", 	64, INSN_CLASS_ZBA, "d,s,t", 	MATCH_ADD_UW, MASK_ADD_UW, match_opcode, 0},
 {"addi", 	0, INSN_CLASS_I, "d,s,j", 	MATCH_ADDI, MASK_ADDI, match_opcode, 0},
 {"addiw", 	64, INSN_CLASS_I, "d,s,j", 	MATCH_ADDIW, MASK_ADDIW, match_opcode, 0},
 {"addw", 	64, INSN_CLASS_I, "d,s,t", 	MATCH_ADDW, MASK_ADDW, match_opcode, 0},
 {"amoadd.b", 	0, INSN_CLASS_A, "d,t,0(s)", 	MATCH_AMOADD_B, MASK_AMOADD_B|MASK_AQRL, match_opcode, INSN_DREF|INSN_1_BYTE},
 {"amoadd.d", 	64, INSN_CLASS_A, "d,t,0(s)", 	MATCH_AMOADD_D, MASK_AMOADD_D|MASK_AQRL, match_opcode, INSN_DREF|INSN_8_BYTE},
 {"amoadd.h", 	0, INSN_CLASS_A, "d,t,0(s)", 	MATCH_AMOADD_H, MASK_AMOADD_H|MASK_AQRL, match_opcode, INSN_DREF|INSN_2_BYTE},
 {"amoadd.w", 	0, INSN_CLASS_A, "d,t,0(s)", 	MATCH_AMOADD_W, MASK_AMOADD_W|MASK_AQRL, match_opcode, INSN_DREF|INSN_4_BYTE},
 {"amoand.b", 	0, INSN_CLASS_A, "d,t,0(s)", 	MATCH_AMOAND_B, MASK_AMOAND_B|MASK_AQRL, match_opcode, INSN_DREF|INSN_1_BYTE},
 {"amoand.d", 	64, INSN_CLASS_A, "d,t,0(s)", 	MATCH_AMOAND_D, MASK_AMOAND_D|MASK_AQRL, match_opcode, INSN_DREF|INSN_8_BYTE},
 {"amoand.h", 	0, INSN_CLASS_A, "d,t,0(s)", 	MATCH_AMOAND_H, MASK_AMOAND_H|MASK_AQRL, match_opcode, INSN_DREF|INSN_2_BYTE},
 {"amoand.w", 	0, INSN_CLASS_A, "d,t,0(s)", 	MATCH_AMOAND_W, MASK_AMOAND_W|MASK_AQRL, match_opcode, INSN_DREF|INSN_4_BYTE},
 {"amomax.b", 	0, INSN_CLASS_A, "d,t,0(s)", 	MATCH_AMOMAX_B, MASK_AMOMAX_B|MASK_AQRL, match_opcode, INSN_DREF|INSN_1_BYTE},
 {"amomax.d", 	64, INSN_CLASS_A, "d,t,0(s)", 	MATCH_AMOMAX_D, MASK_AMOMAX_D|MASK_AQRL, match_opcode, INSN_DREF|INSN_8_BYTE},
 {"amomax.h", 	0, INSN_CLASS_A, "d,t,0(s)", 	MATCH_AMOMAX_H, MASK_AMOMAX_H|MASK_AQRL, match_opcode, INSN_DREF|INSN_2_BYTE},
 {"amomax.w", 	0, INSN_CLASS_A, "d,t,0(s)", 	MATCH_AMOMAX_W, MASK_AMOMAX_W|MASK_AQRL, match_opcode, INSN_DREF|INSN_4_BYTE},
 {"amomaxu.b", 	0, INSN_CLASS_A, "d,t,0(s)", 	MATCH_AMOMAXU_B, MASK_AMOMAXU_B|MASK_AQRL, match_opcode, INSN_DREF|INSN_1_BYTE},
 {"amomaxu.d", 	64, INSN_CLASS_A, "d,t,0(s)", 	MATCH_AMOMAXU_D, MASK_AMOMAXU_D|MASK_AQRL, match_opcode, INSN_DREF|INSN_8_BYTE},
 {"amomaxu.h", 	0, INSN_CLASS_A, "d,t,0(s)", 	MATCH_AMOMAXU_H, MASK_AMOMAXU_H|MASK_AQRL, match_opcode, INSN_DREF|INSN_2_BYTE},
 {"amomaxu.w", 	0, INSN_CLASS_A, "d,t,0(s)", 	MATCH_AMOMAXU_W, MASK_AMOMAXU_W|MASK_AQRL, match_opcode, INSN_DREF|INSN_4_BYTE},
 {"amomin.b", 	0, INSN_CLASS_A, "d,t,0(s)", 	MATCH_AMOMIN_B, MASK_AMOMIN_B|MASK_AQRL, match_opcode, INSN_DREF|INSN_1_BYTE},
 {"amomin.d", 	64, INSN_CLASS_A, "d,t,0(s)", 	MATCH_AMOMIN_D, MASK_AMOMIN_D|MASK_AQRL, match_opcode, INSN_DREF|INSN_8_BYTE},
 {"amomin.h", 	0, INSN_CLASS_A, "d,t,0(s)", 	MATCH_AMOMIN_H, MASK_AMOMIN_H|MASK_AQRL, match_opcode, INSN_DREF|INSN_2_BYTE},
 {"amomin.w", 	0, INSN_CLASS_A, "d,t,0(s)", 	MATCH_AMOMIN_W, MASK_AMOMIN_W|MASK_AQRL, match_opcode, INSN_DREF|INSN_4_BYTE},
 {"amominu.b", 	0, INSN_CLASS_A, "d,t,0(s)", 	MATCH_AMOMINU_B, MASK_AMOMINU_B|MASK_AQRL, match_opcode, INSN_DREF|INSN_1_BYTE},
 {"amominu.d", 	64, INSN_CLASS_A, "d,t,0(s)", 	MATCH_AMOMINU_D, MASK_AMOMINU_D|MASK_AQRL, match_opcode, INSN_DREF|INSN_8_BYTE},
 {"amominu.h", 	0, INSN_CLASS_A, "d,t,0(s)", 	MATCH_AMOMINU_H, MASK_AMOMINU_H|MASK_AQRL, match_opcode, INSN_DREF|INSN_2_BYTE},
 {"amominu.w", 	0, INSN_CLASS_A, "d,t,0(s)", 	MATCH_AMOMINU_W, MASK_AMOMINU_W|MASK_AQRL, match_opcode, INSN_DREF|INSN_4_BYTE},
 {"amoor.b", 	0, INSN_CLASS_A, "d,t,0(s)", 	MATCH_AMOOR_B, MASK_AMOOR_B|MASK_AQRL, match_opcode, INSN_DREF|INSN_1_BYTE},
 {"amoor.d", 	64, INSN_CLASS_A, "d,t,0(s)", 	MATCH_AMOOR_D, MASK_AMOOR_D|MASK_AQRL, match_opcode, INSN_DREF|INSN_8_BYTE},
 {"amoor.h", 	0, INSN_CLASS_A, "d,t,0(s)", 	MATCH_AMOOR_H, MASK_AMOOR_H|MASK_AQRL, match_opcode, INSN_DREF|INSN_2_BYTE},
 {"amoor.w", 	0, INSN_CLASS_A, "d,t,0(s)", 	MATCH_AMOOR_W, MASK_AMOOR_W|MASK_AQRL, match_opcode, INSN_DREF|INSN_4_BYTE},
 {"amoswap.b", 	0, INSN_CLASS_A, "d,t,0(s)", 	MATCH_AMOSWAP_B, MASK_AMOSWAP_B|MASK_AQRL, match_opcode, INSN_DREF|INSN_1_BYTE},
 {"amoswap.d", 	64, INSN_CLASS_A, "d,t,0(s)", 	MATCH_AMOSWAP_D, MASK_AMOSWAP_D|MASK_AQRL, match_opcode, INSN_DREF|INSN_4_BYTE},
 {"amoswap.h", 	0, INSN_CLASS_A, "d,t,0(s)", 	MATCH_AMOSWAP_H, MASK_AMOSWAP_H|MASK_AQRL, match_opcode, INSN_DREF|INSN_2_BYTE},
 {"amoswap.w", 	0, INSN_CLASS_A, "d,t,0(s)", 	MATCH_AMOSWAP_W, MASK_AMOSWAP_W|MASK_AQRL, match_opcode, INSN_DREF|INSN_4_BYTE},
 {"amoxor.b", 	0, INSN_CLASS_A, "d,t,0(s)", 	MATCH_AMOXOR_B, MASK_AMOXOR_B|MASK_AQRL, match_opcode, INSN_DREF|INSN_1_BYTE},
 {"amoxor.d", 	64, INSN_CLASS_A, "d,t,0(s)", 	MATCH_AMOXOR_D, MASK_AMOXOR_D|MASK_AQRL, match_opcode, INSN_DREF|INSN_8_BYTE},
 {"amoxor.h", 	0, INSN_CLASS_A, "d,t,0(s)", 	MATCH_AMOXOR_H, MASK_AMOXOR_H|MASK_AQRL, match_opcode, INSN_DREF|INSN_2_BYTE},
 {"amoxor.w", 	0, INSN_CLASS_A, "d,t,0(s)", 	MATCH_AMOXOR_W, MASK_AMOXOR_W|MASK_AQRL, match_opcode, INSN_DREF|INSN_4_BYTE},
 {"and", 	0, INSN_CLASS_I, "d,s,t", 	MATCH_AND, MASK_AND, match_opcode, 0},
 {"andi", 	0, INSN_CLASS_I, "d,s,j", 	MATCH_ANDI, MASK_ANDI, match_opcode, 0},
 {"andn", 	0, INSN_CLASS_ZBB_OR_ZBKB, "d,s,t", 	MATCH_ANDN, MASK_ANDN, match_opcode, 0},
 {"auipc", 	0, INSN_CLASS_I, "d,u", 	MATCH_AUIPC, MASK_AUIPC, match_opcode, 0},
 {"bclr", 	0, INSN_CLASS_ZBS, "d,s,t", 	MATCH_BCLR, MASK_BCLR, match_opcode, 0},
 {"bclri", 	0, INSN_CLASS_ZBS, "d,s,>", 	MATCH_BCLRI, MASK_BCLRI, match_opcode, 0},
 {"beq", 	0, INSN_CLASS_I, "s,t,p", 	MATCH_BEQ, MASK_BEQ, match_opcode, INSN_CONDBRANCH},
 {"bext", 	0, INSN_CLASS_ZBS, "d,s,t", 	MATCH_BEXT, MASK_BEXT, match_opcode, 0},
 {"bexti", 	0, INSN_CLASS_ZBS, "d,s,>", 	MATCH_BEXTI, MASK_BEXTI, match_opcode, 0},
 {"bge", 	0, INSN_CLASS_I, "s,t,p", 	MATCH_BGE, MASK_BGE, match_opcode, INSN_CONDBRANCH},
 {"bgeu", 	0, INSN_CLASS_I, "s,t,p", 	MATCH_BGEU, MASK_BGEU, match_opcode, INSN_CONDBRANCH},
 {"binv", 	0, INSN_CLASS_ZBS, "d,s,t", 	MATCH_BINV, MASK_BINV, match_opcode, 0},
 {"binvi", 	0, INSN_CLASS_ZBS, "d,s,>", 	MATCH_BINVI, MASK_BINVI, match_opcode, 0},
 {"blt", 	0, INSN_CLASS_I, "s,t,p", 	MATCH_BLT, MASK_BLT, match_opcode, INSN_CONDBRANCH},
 {"bltu", 	0, INSN_CLASS_I, "s,t,p", 	MATCH_BLTU, MASK_BLTU, match_opcode, INSN_CONDBRANCH},
 {"bne", 	0, INSN_CLASS_I, "s,t,p", 	MATCH_BNE, MASK_BNE, match_opcode, INSN_CONDBRANCH},
 {"brev8", 	64, INSN_CLASS_ZBKB, "d,s", MATCH_GREVI | MATCH_SHAMT_BREV8, MASK_GREVI | MASK_SHAMT, match_opcode, 0},
 {"bset", 	0, INSN_CLASS_ZBS, "d,s,t", 	MATCH_BSET, MASK_BSET, match_opcode, 0},
 {"bseti", 	0, INSN_CLASS_ZBS, "d,s,>", 	MATCH_BSETI, MASK_BSETI, match_opcode, 0},
 {"clmul", 	0, INSN_CLASS_ZBC_OR_ZBKC, "d,s,t", 	MATCH_CLMUL, MASK_CLMUL, match_opcode, 0},
 {"clmulh", 	0, INSN_CLASS_ZBC_OR_ZBKC, "d,s,t", 	MATCH_CLMULH, MASK_CLMULH, match_opcode, 0},
 {"clmulr", 	0, INSN_CLASS_ZBC, "d,s,t", 	MATCH_CLMULR, MASK_CLMULR, match_opcode, 0},
 {"clz", 	0, INSN_CLASS_ZBB, "d,s", 	MATCH_CLZ, MASK_CLZ, match_opcode, 0},
 {"clzw", 	0, INSN_CLASS_ZBB, "d,s", 	MATCH_CLZW, MASK_CLZW, match_opcode, 0},
 {"cpop", 	0, INSN_CLASS_ZBB, "d,s", 	MATCH_CPOP, MASK_CPOP, match_opcode, 0},
 {"cpopw", 	0, INSN_CLASS_ZBB, "d,s", 	MATCH_CPOPW, MASK_CPOPW, match_opcode, 0},
 {"csrrc", 	0, INSN_CLASS_ZICSR, "d,E,s", 	MATCH_CSRRC, MASK_CSRRC, match_opcode, 0},
 {"csrrci", 	0, INSN_CLASS_ZICSR, "d,E,Z", 	MATCH_CSRRCI, MASK_CSRRCI, match_opcode, 0},
 {"csrrs", 	0, INSN_CLASS_ZICSR, "d,E,s", 	MATCH_CSRRS, MASK_CSRRS, match_opcode, 0},
 {"csrrsi", 	0, INSN_CLASS_ZICSR, "d,E,Z", 	MATCH_CSRRSI, MASK_CSRRSI, match_opcode, 0},
 {"csrrw", 	0, INSN_CLASS_ZICSR, "d,E,s", 	MATCH_CSRRW, MASK_CSRRW, match_opcode, 0},
 {"csrrwi", 	0, INSN_CLASS_ZICSR, "d,E,Z", 	MATCH_CSRRWI, MASK_CSRRWI, match_opcode, 0},
 {"ctz", 	0, INSN_CLASS_ZBB, "d,s", 	MATCH_CTZ, MASK_CTZ, match_opcode, 0},
 {"ctzw", 	0, INSN_CLASS_ZBB, "d,s", 	MATCH_CTZW, MASK_CTZW, match_opcode, 0},
 {"czero.eqz", 	0, INSN_CLASS_ZICOND, "d,s,t", 	MATCH_CZERO_EQZ, MASK_CZERO_EQZ, match_opcode, 0},
 {"czero.nez", 	0, INSN_CLASS_ZICOND, "d,s,t", 	MATCH_CZERO_NEZ, MASK_CZERO_NEZ, match_opcode, 0},
 {"div", 	0, INSN_CLASS_M, "d,s,t", 	MATCH_DIV, MASK_DIV, match_opcode, 0},
 {"divu", 	0, INSN_CLASS_M, "d,s,t", 	MATCH_DIVU, MASK_DIVU, match_opcode, 0},
 {"divuw", 	64, INSN_CLASS_M, "d,s,t", 	MATCH_DIVUW, MASK_DIVUW, match_opcode, 0},
 {"divw", 	64, INSN_CLASS_M, "d,s,t", 	MATCH_DIVW, MASK_DIVW, match_opcode, 0},
 {"ebreak", 	0, INSN_CLASS_I, "", 	MATCH_EBREAK, MASK_EBREAK, match_opcode, 0},
 {"ecall", 	0, INSN_CLASS_I, "", 	MATCH_ECALL, MASK_ECALL, match_opcode, 0},
 {"fadd.d", 	0, INSN_CLASS_D_INX, "D,S,T", 	MATCH_FADD_D|MASK_RM, MASK_FADD_D|MASK_RM, match_opcode, 0},
 {"fadd.d", 	0, INSN_CLASS_D_INX, "D,S,T,m", 	MATCH_FADD_D, MASK_FADD_D, match_opcode, 0},
 {"fadd.h", 	0, INSN_CLASS_ZFH_INX, "D,S,T", 	MATCH_FADD_H|MASK_RM, MASK_FADD_H|MASK_RM, match_opcode, 0},
 {"fadd.h", 	0, INSN_CLASS_ZFH_INX, "D,S,T,m", 	MATCH_FADD_H, MASK_FADD_H, match_opcode, 0},
 {"fadd.s", 	0, INSN_CLASS_F_INX, "D,S,T", 	MATCH_FADD_S|MASK_RM, MASK_FADD_S|MASK_RM, match_opcode, 0},
 {"fadd.s", 	0, INSN_CLASS_F_INX, "D,S,T,m", 	MATCH_FADD_S, MASK_FADD_S, match_opcode, 0},
 {"fclass.d", 	0, INSN_CLASS_D_INX, "d,S", 	MATCH_FCLASS_D, MASK_FCLASS_D, match_opcode, 0},
 {"fclass.h", 	0, INSN_CLASS_ZFH_INX, "d,S", 	MATCH_FCLASS_H, MASK_FCLASS_H, match_opcode, 0},
 {"fclass.s", 	0, INSN_CLASS_F_INX, "d,S", 	MATCH_FCLASS_S, MASK_FCLASS_S, match_opcode, 0},
 {"fcvt.d.h", 	0, INSN_CLASS_ZFH_INX, "D,S", 	MATCH_FCVT_D_H|MASK_RM, MASK_FCVT_D_H|MASK_RM, match_opcode, 0},
 {"fcvt.d.h", 	0, INSN_CLASS_ZFH_INX, "D,S,m", 	MATCH_FCVT_D_H, MASK_FCVT_D_H, match_opcode, 0},
 {"fcvt.d.l", 	64, INSN_CLASS_D_INX, "D,s", 	MATCH_FCVT_D_L|MASK_RM, MASK_FCVT_D_L|MASK_RM, match_opcode, 0},
 {"fcvt.d.l", 	64, INSN_CLASS_D_INX, "D,s,m", 	MATCH_FCVT_D_L, MASK_FCVT_D_L, match_opcode, 0},
 {"fcvt.d.lu", 	64, INSN_CLASS_D_INX, "D,s", 	MATCH_FCVT_D_LU|MASK_RM, MASK_FCVT_D_LU|MASK_RM, match_opcode, 0},
 {"fcvt.d.lu", 	64, INSN_CLASS_D_INX, "D,s,m", 	MATCH_FCVT_D_LU, MASK_FCVT_D_LU, match_opcode, 0},
 {"fcvt.d.s", 	0, INSN_CLASS_D_INX, "D,S", 	MATCH_FCVT_D_S, MASK_FCVT_D_S|MASK_RM, match_opcode, 0},
 {"fcvt.d.s", 	0, INSN_CLASS_D_INX, "D,S,m", 	MATCH_FCVT_D_S, MASK_FCVT_D_S, match_opcode, 0},
 {"fcvt.d.w", 	0, INSN_CLASS_D_INX, "D,s", 	MATCH_FCVT_D_W, MASK_FCVT_D_W|MASK_RM, match_opcode, 0},
 {"fcvt.d.w", 	0, INSN_CLASS_D_INX, "D,s,m", 	MATCH_FCVT_D_W, MASK_FCVT_D_W, match_opcode, 0},
 {"fcvt.d.wu", 	0, INSN_CLASS_D_INX, "D,s", 	MATCH_FCVT_D_WU|MASK_RM, MASK_FCVT_D_WU|MASK_RM, match_opcode, 0},
 {"fcvt.d.wu", 	0, INSN_CLASS_D_INX, "D,s,m", 	MATCH_FCVT_D_WU, MASK_FCVT_D_WU, match_opcode, 0},
 {"fcvt.h.d", 	0, INSN_CLASS_ZFH_INX, "D,S", 	MATCH_FCVT_H_D|MASK_RM, MASK_FCVT_H_D|MASK_RM, match_opcode, 0},
 {"fcvt.h.d", 	0, INSN_CLASS_ZFH_INX, "D,S,m", 	MATCH_FCVT_H_D, MASK_FCVT_H_D, match_opcode, 0},
 {"fcvt.h.l", 	64, INSN_CLASS_ZFH_INX, "D,s", 	MATCH_FCVT_H_L|MASK_RM, MASK_FCVT_H_L|MASK_RM, match_opcode, 0},
 {"fcvt.h.l", 	64, INSN_CLASS_ZFH_INX, "D,s,m", 	MATCH_FCVT_H_L, MASK_FCVT_H_L, match_opcode, 0},
 {"fcvt.h.lu", 	64, INSN_CLASS_ZFH_INX, "D,s", 	MATCH_FCVT_H_LU|MASK_RM, MASK_FCVT_H_LU|MASK_RM, match_opcode, 0},
 {"fcvt.h.lu", 	64, INSN_CLASS_ZFH_INX, "D,s,m", 	MATCH_FCVT_H_LU, MASK_FCVT_H_LU, match_opcode, 0},
 {"fcvt.h.s", 	0, INSN_CLASS_ZFH_INX, "D,S", 	MATCH_FCVT_H_S|MASK_RM, MASK_FCVT_H_S|MASK_RM, match_opcode, 0},
 {"fcvt.h.s", 	0, INSN_CLASS_ZFH_INX, "D,S,m", 	MATCH_FCVT_H_S, MASK_FCVT_H_S, match_opcode, 0},
 {"fcvt.h.w", 	0, INSN_CLASS_ZFH_INX, "D,s", 	MATCH_FCVT_H_W|MASK_RM, MASK_FCVT_H_W|MASK_RM, match_opcode, 0},
 {"fcvt.h.w", 	0, INSN_CLASS_ZFH_INX, "D,s,m", 	MATCH_FCVT_H_W, MASK_FCVT_H_W, match_opcode, 0},
 {"fcvt.h.wu", 	0, INSN_CLASS_ZFH_INX, "D,s", 	MATCH_FCVT_H_WU|MASK_RM, MASK_FCVT_H_WU|MASK_RM, match_opcode, 0},
 {"fcvt.h.wu", 	0, INSN_CLASS_ZFH_INX, "D,s,m", 	MATCH_FCVT_H_WU, MASK_FCVT_H_WU, match_opcode, 0},
 {"fcvt.l.d", 	64, INSN_CLASS_D_INX, "d,S", 	MATCH_FCVT_L_D|MASK_RM, MASK_FCVT_L_D|MASK_RM, match_opcode, 0},
 {"fcvt.l.d", 	64, INSN_CLASS_D_INX, "d,S,m", 	MATCH_FCVT_L_D, MASK_FCVT_L_D, match_opcode, 0},
 {"fcvt.l.h", 	64, INSN_CLASS_ZFH_INX, "d,S", 	MATCH_FCVT_L_H|MASK_RM, MASK_FCVT_L_H|MASK_RM, match_opcode, 0},
 {"fcvt.l.h", 	64, INSN_CLASS_ZFH_INX, "d,S,m", 	MATCH_FCVT_L_H, MASK_FCVT_L_H, match_opcode, 0},
 {"fcvt.l.s", 	64, INSN_CLASS_F_INX, "d,S", 	MATCH_FCVT_L_S|MASK_RM, MASK_FCVT_L_S|MASK_RM, match_opcode, 0},
 {"fcvt.l.s", 	64, INSN_CLASS_F_INX, "d,S,m", 	MATCH_FCVT_L_S, MASK_FCVT_L_S, match_opcode, 0},
 {"fcvt.lu.d", 	64, INSN_CLASS_D_INX, "d,S", 	MATCH_FCVT_LU_D|MASK_RM, MASK_FCVT_LU_D|MASK_RM, match_opcode, 0},
 {"fcvt.lu.d", 	64, INSN_CLASS_D_INX, "d,S,m", 	MATCH_FCVT_LU_D, MASK_FCVT_LU_D, match_opcode, 0},
 {"fcvt.lu.h", 	64, INSN_CLASS_ZFH_INX, "d,S", 	MATCH_FCVT_LU_H|MASK_RM, MASK_FCVT_LU_H|MASK_RM, match_opcode, 0},
 {"fcvt.lu.h", 	64, INSN_CLASS_ZFH_INX, "d,S,m", 	MATCH_FCVT_LU_H, MASK_FCVT_LU_H, match_opcode, 0},
 {"fcvt.lu.s", 	64, INSN_CLASS_F_INX, "d,S", 	MATCH_FCVT_LU_S|MASK_RM, MASK_FCVT_LU_S|MASK_RM, match_opcode, 0},
 {"fcvt.lu.s", 	64, INSN_CLASS_F_INX, "d,S,m", 	MATCH_FCVT_LU_S, MASK_FCVT_LU_S, match_opcode, 0},
 {"fcvt.s.d", 	0, INSN_CLASS_D_INX, "D,S", 	MATCH_FCVT_S_D|MASK_RM, MASK_FCVT_S_D|MASK_RM, match_opcode, 0},
 {"fcvt.s.d", 	0, INSN_CLASS_D_INX, "D,S,m", 	MATCH_FCVT_S_D, MASK_FCVT_S_D, match_opcode, 0},
 {"fcvt.s.h", 	0, INSN_CLASS_ZFH_INX, "D,S", 	MATCH_FCVT_S_H|MASK_RM, MASK_FCVT_S_H|MASK_RM, match_opcode, 0},
 {"fcvt.s.h", 	0, INSN_CLASS_ZFH_INX, "D,S,m", 	MATCH_FCVT_S_H, MASK_FCVT_S_H, match_opcode, 0},
 {"fcvt.s.l", 	64, INSN_CLASS_F_INX, "D,s", 	MATCH_FCVT_S_L|MASK_RM, MASK_FCVT_S_L|MASK_RM, match_opcode, 0},
 {"fcvt.s.l", 	64, INSN_CLASS_F_INX, "D,s,m", 	MATCH_FCVT_S_L, MASK_FCVT_S_L, match_opcode, 0},
 {"fcvt.s.lu", 	64, INSN_CLASS_F_INX, "D,s", 	MATCH_FCVT_S_LU|MASK_RM, MASK_FCVT_S_LU|MASK_RM, match_opcode, 0},
 {"fcvt.s.lu", 	64, INSN_CLASS_F_INX, "D,s,m", 	MATCH_FCVT_S_LU, MASK_FCVT_S_LU, match_opcode, 0},
 {"fcvt.s.w", 	0, INSN_CLASS_F_INX, "D,s", 	MATCH_FCVT_S_W|MASK_RM, MASK_FCVT_S_W|MASK_RM, match_opcode, 0},
 {"fcvt.s.w", 	0, INSN_CLASS_F_INX, "D,s,m", 	MATCH_FCVT_S_W, MASK_FCVT_S_W, match_opcode, 0},
 {"fcvt.s.wu", 	0, INSN_CLASS_F_INX, "D,s", 	MATCH_FCVT_S_WU|MASK_RM, MASK_FCVT_S_WU|MASK_RM, match_opcode, 0},
 {"fcvt.s.wu", 	0, INSN_CLASS_F_INX, "D,s,m", 	MATCH_FCVT_S_WU, MASK_FCVT_S_WU, match_opcode, 0},
 {"fcvt.w.d", 	0, INSN_CLASS_D_INX, "d,S", 	MATCH_FCVT_W_D|MASK_RM, MASK_FCVT_W_D|MASK_RM, match_opcode, 0},
 {"fcvt.w.d", 	0, INSN_CLASS_D_INX, "d,S,m", 	MATCH_FCVT_W_D, MASK_FCVT_W_D, match_opcode, 0},
 {"fcvt.w.h", 	0, INSN_CLASS_ZFH_INX, "d,S", 	MATCH_FCVT_W_H|MASK_RM, MASK_FCVT_W_H|MASK_RM, match_opcode, 0},
 {"fcvt.w.h", 	0, INSN_CLASS_ZFH_INX, "d,S,m", 	MATCH_FCVT_W_H, MASK_FCVT_W_H, match_opcode, 0},
 {"fcvt.w.s", 	0, INSN_CLASS_F_INX, "d,S", 	MATCH_FCVT_W_S|MASK_RM, MASK_FCVT_W_S|MASK_RM, match_opcode, 0},
 {"fcvt.w.s", 	0, INSN_CLASS_F_INX, "d,S,m", 	MATCH_FCVT_W_S, MASK_FCVT_W_S, match_opcode, 0},
 {"fcvt.wu.d", 	0, INSN_CLASS_D_INX, "d,S", 	MATCH_FCVT_WU_D|MASK_RM, MASK_FCVT_WU_D|MASK_RM, match_opcode, 0},
 {"fcvt.wu.d", 	0, INSN_CLASS_D_INX, "d,S,m", 	MATCH_FCVT_WU_D, MASK_FCVT_WU_D, match_opcode, 0},
 {"fcvt.wu.h", 	0, INSN_CLASS_ZFH_INX, "d,S", 	MATCH_FCVT_WU_H|MASK_RM, MASK_FCVT_WU_H|MASK_RM, match_opcode, 0},
 {"fcvt.wu.h", 	0, INSN_CLASS_ZFH_INX, "d,S,m", 	MATCH_FCVT_WU_H, MASK_FCVT_WU_H, match_opcode, 0},
 {"fcvt.wu.s", 	0, INSN_CLASS_F_INX, "d,S", 	MATCH_FCVT_WU_S|MASK_RM, MASK_FCVT_WU_S|MASK_RM, match_opcode, 0},
 {"fcvt.wu.s", 	0, INSN_CLASS_F_INX, "d,S,m", 	MATCH_FCVT_WU_S, MASK_FCVT_WU_S, match_opcode, 0},
 {"fcvtmod.w.d", 	0, INSN_CLASS_D_AND_ZFA, "d,S", 	MATCH_FCVTMOD_W_D, MASK_FCVTMOD_W_D, match_opcode, 0},
 {"fdiv.d", 	0, INSN_CLASS_D_INX, "D,S,T", 	MATCH_FDIV_D|MASK_RM, MASK_FDIV_D|MASK_RM, match_opcode, 0},
 {"fdiv.d", 	0, INSN_CLASS_D_INX, "D,S,T,m", 	MATCH_FDIV_D, MASK_FDIV_D, match_opcode, 0},
 {"fdiv.h", 	0, INSN_CLASS_ZFH_INX, "D,S,T", 	MATCH_FDIV_H|MASK_RM, MASK_FDIV_H|MASK_RM, match_opcode, 0},
 {"fdiv.h", 	0, INSN_CLASS_ZFH_INX, "D,S,T,m", 	MATCH_FDIV_H, MASK_FDIV_H, match_opcode, 0},
 {"fdiv.s", 	0, INSN_CLASS_F_INX, "D,S,T", 	MATCH_FDIV_S|MASK_RM, MASK_FDIV_S|MASK_RM, match_opcode, 0},
 {"fdiv.s", 	0, INSN_CLASS_F_INX, "D,S,T,m", 	MATCH_FDIV_S, MASK_FDIV_S, match_opcode, 0},
 {"fence", 	0, INSN_CLASS_I, "P,Q", 	MATCH_FENCE, MASK_FENCE|MASK_RD|MASK_RS1|(MASK_IMM & ~MASK_PRED & ~MASK_SUCC), match_opcode, 0},
 {"fence_tso", 	0, INSN_CLASS_I, "", 	MATCH_FENCE_TSO, MASK_FENCE_TSO|MASK_RD|MASK_RS1, match_opcode, 0},
 {"fencei", 	0, INSN_CLASS_ZIFENCEI, "", 	MATCH_FENCEI, MASK_FENCE|MASK_RD|MASK_RS1|MASK_IMM, match_opcode, 0},
 {"feq.d", 	0, INSN_CLASS_D_INX, "d,S,T", 	MATCH_FEQ_D, MASK_FEQ_D, match_opcode, 0},
 {"feq.h", 	0, INSN_CLASS_ZFH_INX, "d,S,T", 	MATCH_FEQ_H, MASK_FEQ_H, match_opcode, 0},
 {"feq.s", 	0, INSN_CLASS_F_INX, "d,S,T", 	MATCH_FEQ_S, MASK_FEQ_S, match_opcode, 0},
 {"fld", 	0, INSN_CLASS_I, "D,o(s)", 	MATCH_FLD, MASK_FLD, match_opcode, INSN_DREF|INSN_8_BYTE},
 {"fle.d", 	0, INSN_CLASS_D_INX, "d,S,T", 	MATCH_FLE_D, MASK_FLE_D, match_opcode, 0},
 {"fle.h", 	0, INSN_CLASS_ZFH_INX, "d,S,T", 	MATCH_FLE_H, MASK_FLE_H, match_opcode, 0},
 {"fle.s", 	0, INSN_CLASS_F_INX, "d,S,T", 	MATCH_FLE_S, MASK_FLE_S, match_opcode, 0},
 {"fleq.d", 	0, INSN_CLASS_D_AND_ZFA, "D,S,T", 	MATCH_FLEQ_D, MASK_FLEQ_D, match_opcode, 0},
 {"fleq.h", 	0, INSN_CLASS_ZFH_AND_ZFA, "D,S,T", 	MATCH_FLEQ_H, MASK_FLEQ_H, match_opcode, 0},
 {"fleq.s", 	0, INSN_CLASS_ZFA, "D,S,T", 	MATCH_FLEQ_S, MASK_FLEQ_S, match_opcode, 0},
 {"flh", 	0, INSN_CLASS_I, "D,o(s)", 	MATCH_FLH, MASK_FLH, match_opcode, INSN_DREF|INSN_2_BYTE},
 {"fli.d", 	0, INSN_CLASS_D_AND_ZFA, "D", 	MATCH_FLI_D, MASK_FLI_D, match_opcode, 0},
 {"fli.h", 	0, INSN_CLASS_ZFH_OR_ZVFH_AND_ZFA, "D", 	MATCH_FLI_H, MASK_FLI_H, match_opcode, 0},
 {"fli.s", 	0, INSN_CLASS_ZFA, "D", 	MATCH_FLI_S, MASK_FLI_S, match_opcode, 0},
 {"flt.d", 	0, INSN_CLASS_D_INX, "d,S,T", 	MATCH_FLT_D, MASK_FLT_D, match_opcode, 0},
 {"flt.h", 	0, INSN_CLASS_ZFH_INX, "d,S,T", 	MATCH_FLT_H, MASK_FLT_H, match_opcode, 0},
 {"flt.s", 	0, INSN_CLASS_F_INX, "d,S,T", 	MATCH_FLT_S, MASK_FLT_S, match_opcode, 0},
 {"fltq.d", 	0, INSN_CLASS_D_AND_ZFA, "D,S,T", 	MATCH_FLTQ_D, MASK_FLTQ_D, match_opcode, 0},
 {"fltq.h", 	0, INSN_CLASS_ZFH_AND_ZFA, "D,S,T", 	MATCH_FLTQ_H, MASK_FLTQ_H, match_opcode, 0},
 {"fltq.s", 	0, INSN_CLASS_ZFA, "D,S,T", 	MATCH_FLTQ_S, MASK_FLTQ_S, match_opcode, 0},
 {"flw", 	0, INSN_CLASS_I, "D,o(s)", 	MATCH_FLW, MASK_FLW, match_opcode, INSN_DREF|INSN_4_BYTE},
 {"fmadd.d", 	0, INSN_CLASS_D_INX, "D,S,T,R", 	MATCH_FMADD_D|MASK_RM, MASK_FMADD_D|MASK_RM, match_opcode, 0},
 {"fmadd.d", 	0, INSN_CLASS_D_INX, "D,S,T,R,m", 	MATCH_FMADD_D, MASK_FMADD_D, match_opcode, 0},
 {"fmadd.h", 	0, INSN_CLASS_ZFH_INX, "D,S,T,R", 	MATCH_FMADD_H|MASK_RM, MASK_FMADD_H|MASK_RM, match_opcode, 0},
 {"fmadd.h", 	0, INSN_CLASS_ZFH_INX, "D,S,T,R,m", 	MATCH_FMADD_H, MASK_FMADD_H, match_opcode, 0},
 {"fmadd.s", 	0, INSN_CLASS_F_INX, "D,S,T,R", 	MATCH_FMADD_S|MASK_RM, MASK_FMADD_S|MASK_RM, match_opcode, 0},
 {"fmadd.s", 	0, INSN_CLASS_F_INX, "D,S,T,R,m", 	MATCH_FMADD_S, MASK_FMADD_S, match_opcode, 0},
 {"fmax.d", 	0, INSN_CLASS_D_INX, "D,S,T", 	MATCH_FMAX_D, MASK_FMAX_D, match_opcode, 0},
 {"fmax.h", 	0, INSN_CLASS_ZFH_INX, "D,S,T", 	MATCH_FMAX_H, MASK_FMAX_H, match_opcode, 0},
 {"fmax.s", 	0, INSN_CLASS_F_INX, "D,S,T", 	MATCH_FMAX_S, MASK_FMAX_S, match_opcode, 0},
 {"fmaxm.d", 	0, INSN_CLASS_D_AND_ZFA, "D,S,T", 	MATCH_FMAXM_D, MASK_FMAXM_D, match_opcode, 0},
 {"fmaxm.h", 	0, INSN_CLASS_ZFH_AND_ZFA, "D,S,T", 	MATCH_FMAXM_H, MASK_FMAXM_H, match_opcode, 0},
 {"fmaxm.s", 	0, INSN_CLASS_ZFA, "D,S,T", 	MATCH_FMAXM_S, MASK_FMAXM_S, match_opcode, 0},
 {"fmin.d", 	0, INSN_CLASS_D_INX, "D,S,T", 	MATCH_FMIN_D, MASK_FMIN_D, match_opcode, 0},
 {"fmin.h", 	0, INSN_CLASS_ZFH_INX, "D,S,T", 	MATCH_FMIN_H, MASK_FMIN_H, match_opcode, 0},
 {"fmin.s", 	0, INSN_CLASS_F_INX, "D,S,T", 	MATCH_FMIN_S, MASK_FMIN_S, match_opcode, 0},
 {"fminm.d", 	0, INSN_CLASS_D_AND_ZFA, "D,S,T", 	MATCH_FMINM_D, MASK_FMINM_D, match_opcode, 0},
 {"fminm.h", 	0, INSN_CLASS_ZFH_AND_ZFA, "D,S,T", 	MATCH_FMINM_H, MASK_FMINM_H, match_opcode, 0},
 {"fminm.s", 	0, INSN_CLASS_ZFA, "D,S,T", 	MATCH_FMINM_S, MASK_FMINM_S, match_opcode, 0},
 {"fmsub.d", 	0, INSN_CLASS_D_INX, "D,S,T,R", 	MATCH_FMSUB_D|MASK_RM, MASK_FMSUB_D|MASK_RM, match_opcode, 0},
 {"fmsub.d", 	0, INSN_CLASS_D_INX, "D,S,T,R,m", 	MATCH_FMSUB_D, MASK_FMSUB_D, match_opcode, 0},
 {"fmsub.h", 	0, INSN_CLASS_ZFH_INX, "D,S,T,R", 	MATCH_FMSUB_H|MASK_RM, MASK_FMSUB_H|MASK_RM, match_opcode, 0},
 {"fmsub.h", 	0, INSN_CLASS_ZFH_INX, "D,S,T,R,m", 	MATCH_FMSUB_H, MASK_FMSUB_H, match_opcode, 0},
 {"fmsub.s", 	0, INSN_CLASS_F_INX, "D,S,T,R", 	MATCH_FMSUB_S|MASK_RM, MASK_FMSUB_S|MASK_RM, match_opcode, 0},
 {"fmsub.s", 	0, INSN_CLASS_F_INX, "D,S,T,R,m", 	MATCH_FMSUB_S, MASK_FMSUB_S, match_opcode, 0},
 {"fmul.d", 	0, INSN_CLASS_D_INX, "D,S,T", 	MATCH_FMUL_D|MASK_RM, MASK_FMUL_D|MASK_RM, match_opcode, 0},
 {"fmul.d", 	0, INSN_CLASS_D_INX, "D,S,T,m", 	MATCH_FMUL_D, MASK_FMUL_D, match_opcode, 0},
 {"fmul.h", 	0, INSN_CLASS_ZFH_INX, "D,S,T", 	MATCH_FMUL_H|MASK_RM, MASK_FMUL_H|MASK_RM, match_opcode, 0},
 {"fmul.h", 	0, INSN_CLASS_ZFH_INX, "D,S,T,m", 	MATCH_FMUL_H, MASK_FMUL_H, match_opcode, 0},
 {"fmul.s", 	0, INSN_CLASS_F_INX, "D,S,T", 	MATCH_FMUL_S|MASK_RM, MASK_FMUL_S|MASK_RM, match_opcode, 0},
 {"fmul.s", 	0, INSN_CLASS_F_INX, "D,S,T,m", 	MATCH_FMUL_S, MASK_FMUL_S, match_opcode, 0},
 {"fmv.d.x", 	0, INSN_CLASS_D_INX, "D,s", 	MATCH_FMV_D_X, MASK_FMV_D_X, match_opcode, 0},
 {"fmv.h.x", 	0, INSN_CLASS_ZFH_INX, "D,s", 	MATCH_FMV_H_X, MASK_FMV_H_X, match_opcode, 0},
 {"fmv.w.x", 	0, INSN_CLASS_F_INX, "D,s", 	MATCH_FMV_W_X, MASK_FMV_W_X, match_opcode, 0},
 {"fmv.x.d", 	0, INSN_CLASS_D_INX, "d,S", 	MATCH_FMV_X_D, MASK_FMV_X_D, match_opcode, 0},
 {"fmv.x.h", 	0, INSN_CLASS_ZFH_INX, "d,S", 	MATCH_FMV_X_H, MASK_FMV_X_H, match_opcode, 0},
 {"fmv.x.w", 	0, INSN_CLASS_F_INX, "d,S", 	MATCH_FMV_X_W, MASK_FMV_X_W, match_opcode, 0},
 {"fmvh.x.d", 	0, INSN_CLASS_D_AND_ZFA, "d,S", 	MATCH_FMVH_X_D, MASK_FMVH_X_D, match_opcode, 0},
 {"fmvp.d.x", 	0, INSN_CLASS_D_AND_ZFA, "D,s,t", 	MATCH_FMVP_D_X, MASK_FMVP_D_X, match_opcode, 0},
 {"fnmadd.d", 	0, INSN_CLASS_D_INX, "D,S,T,R", 	MATCH_FNMADD_D|MASK_RM, MASK_FNMADD_D|MASK_RM, match_opcode, 0},
 {"fnmadd.d", 	0, INSN_CLASS_D_INX, "D,S,T,R,m", 	MATCH_FNMADD_D, MASK_FNMADD_D, match_opcode, 0},
 {"fnmadd.h", 	0, INSN_CLASS_ZFH_INX, "D,S,T,R", 	MATCH_FNMADD_H|MASK_RM, MASK_FNMADD_H|MASK_RM, match_opcode, 0},
 {"fnmadd.h", 	0, INSN_CLASS_ZFH_INX, "D,S,T,R,m", 	MATCH_FNMADD_H, MASK_FNMADD_H, match_opcode, 0},
 {"fnmadd.s", 	0, INSN_CLASS_F_INX, "D,S,T,R", 	MATCH_FNMADD_S|MASK_RM, MASK_FNMADD_S|MASK_RM, match_opcode, 0},
 {"fnmadd.s", 	0, INSN_CLASS_F_INX, "D,S,T,R,m", 	MATCH_FNMADD_S, MASK_FNMADD_S, match_opcode, 0},
 {"fnmsub.d", 	0, INSN_CLASS_D_INX, "D,S,T,R", 	MATCH_FNMSUB_D|MASK_RM, MASK_FNMSUB_D|MASK_RM, match_opcode, 0},
 {"fnmsub.d", 	0, INSN_CLASS_D_INX, "D,S,T,R,m", 	MATCH_FNMSUB_D, MASK_FNMSUB_D, match_opcode, 0},
 {"fnmsub.h", 	0, INSN_CLASS_ZFH_INX, "D,S,T,R", 	MATCH_FNMSUB_H|MASK_RM, MASK_FNMSUB_H|MASK_RM, match_opcode, 0},
 {"fnmsub.h", 	0, INSN_CLASS_ZFH_INX, "D,S,T,R,m", 	MATCH_FNMSUB_H, MASK_FNMSUB_H, match_opcode, 0},
 {"fnmsub.s", 	0, INSN_CLASS_F_INX, "D,S,T,R", 	MATCH_FNMSUB_S|MASK_RM, MASK_FNMSUB_S|MASK_RM, match_opcode, 0},
 {"fnmsub.s", 	0, INSN_CLASS_F_INX, "D,S,T,R,m", 	MATCH_FNMSUB_S, MASK_FNMSUB_S, match_opcode, 0},
 {"fround.d", 	0, INSN_CLASS_D_AND_ZFA, "D,S", 	MATCH_FROUND_D|MASK_RM, MASK_FROUND_D|MASK_RM, match_opcode, 0},
 {"fround.h", 	0, INSN_CLASS_ZFH_AND_ZFA, "D,S", 	MATCH_FROUND_H|MASK_RM, MASK_FROUND_H|MASK_RM, match_opcode, 0},
 {"fround.s", 	0, INSN_CLASS_ZFA, "D,S", 	MATCH_FROUND_S|MASK_RM, MASK_FROUND_S|MASK_RM, match_opcode, 0},
 {"froundnx.d", 	0, INSN_CLASS_D_AND_ZFA, "D,S", 	MATCH_FROUNDNX_D|MASK_RM, MASK_FROUNDNX_D|MASK_RM, match_opcode, 0},
 {"froundnx.h", 	0, INSN_CLASS_ZFH_AND_ZFA, "D,S", 	MATCH_FROUNDNX_H|MASK_RM, MASK_FROUNDNX_H|MASK_RM, match_opcode, 0},
 {"froundnx.s", 	0, INSN_CLASS_ZFA, "D,S", 	MATCH_FROUNDNX_S|MASK_RM, MASK_FROUNDNX_S|MASK_RM, match_opcode, 0},
 {"fsd", 	0, INSN_CLASS_I, "T,q(s)", 	MATCH_FSD, MASK_FSD, match_opcode, INSN_DREF|INSN_8_BYTE},
 {"fsgnj.d", 	0, INSN_CLASS_D_INX, "D,S,T", 	MATCH_FSGNJ_D, MASK_FSGNJ_D, match_opcode, 0},
 {"fsgnj.h", 	0, INSN_CLASS_ZFH_INX, "D,S,T", 	MATCH_FSGNJ_H, MASK_FSGNJ_H, match_opcode, 0},
 {"fsgnj.s", 	0, INSN_CLASS_F_INX, "D,S,T", 	MATCH_FSGNJ_S, MASK_FSGNJ_S, match_opcode, 0},
 {"fsgnjn.d", 	0, INSN_CLASS_D_INX, "D,S,T", 	MATCH_FSGNJN_D, MASK_FSGNJN_D, match_opcode, 0},
 {"fsgnjn.h", 	0, INSN_CLASS_ZFH_INX, "D,S,T", 	MATCH_FSGNJN_H, MASK_FSGNJN_H, match_opcode, 0},
 {"fsgnjn.s", 	0, INSN_CLASS_F_INX, "D,S,T", 	MATCH_FSGNJN_S, MASK_FSGNJN_S, match_opcode, 0},
 {"fsgnjx.d", 	0, INSN_CLASS_D_INX, "D,S,T", 	MATCH_FSGNJX_D, MASK_FSGNJX_D, match_opcode, 0},
 {"fsgnjx.h", 	0, INSN_CLASS_ZFH_INX, "D,S,T", 	MATCH_FSGNJX_H, MASK_FSGNJX_H, match_opcode, 0},
 {"fsgnjx.s", 	0, INSN_CLASS_F_INX, "D,S,T", 	MATCH_FSGNJX_S, MASK_FSGNJX_S, match_opcode, 0},
 {"fsh", 	0, INSN_CLASS_I, "T,q(s)", 	MATCH_FSH, MASK_FSH, match_opcode, INSN_DREF|INSN_2_BYTE},
 {"fsqrt.d", 	0, INSN_CLASS_D_INX, "D,S", 	MATCH_FSQRT_D|MASK_RM, MASK_FSQRT_D|MASK_RM, match_opcode, 0},
 {"fsqrt.d", 	0, INSN_CLASS_D_INX, "D,S,m", 	MATCH_FSQRT_D, MASK_FSQRT_D, match_opcode, 0},
 {"fsqrt.h", 	0, INSN_CLASS_ZFH_INX, "D,S", 	MATCH_FSQRT_H|MASK_RM, MASK_FSQRT_H|MASK_RM, match_opcode, 0},
 {"fsqrt.h", 	0, INSN_CLASS_ZFH_INX, "D,S,m", 	MATCH_FSQRT_H, MASK_FSQRT_H, match_opcode, 0},
 {"fsqrt.s", 	0, INSN_CLASS_F_INX, "D,S", 	MATCH_FSQRT_S|MASK_RM, MASK_FSQRT_S|MASK_RM, match_opcode, 0},
 {"fsqrt.s", 	0, INSN_CLASS_F_INX, "D,S,m", 	MATCH_FSQRT_S, MASK_FSQRT_S, match_opcode, 0},
 {"fsub.d", 	0, INSN_CLASS_D_INX, "D,S,T", 	MATCH_FSUB_D|MASK_RM, MASK_FSUB_D|MASK_RM, match_opcode, 0},
 {"fsub.d", 	0, INSN_CLASS_D_INX, "D,S,T,m", 	MATCH_FSUB_D, MASK_FSUB_D, match_opcode, 0},
 {"fsub.h", 	0, INSN_CLASS_ZFH_INX, "D,S,T", 	MATCH_FSUB_H|MASK_RM, MASK_FSUB_H|MASK_RM, match_opcode, 0},
 {"fsub.h", 	0, INSN_CLASS_ZFH_INX, "D,S,T,m", 	MATCH_FSUB_H, MASK_FSUB_H, match_opcode, 0},
 {"fsub.s", 	0, INSN_CLASS_F_INX, "D,S,T", 	MATCH_FSUB_S|MASK_RM, MASK_FSUB_S|MASK_RM, match_opcode, 0},
 {"fsub.s", 	0, INSN_CLASS_F_INX, "D,S,T,m", 	MATCH_FSUB_S, MASK_FSUB_S, match_opcode, 0},
 {"fsw", 	0, INSN_CLASS_I, "T,q(s)", 	MATCH_FSW, MASK_FSW, match_opcode, INSN_DREF|INSN_4_BYTE},
 {"jal", 	0, INSN_CLASS_I, "d,a", 	MATCH_JAL, MASK_JAL, match_opcode, INSN_JSR},
 {"jalr", 	0, INSN_CLASS_I, "d,j,s", 	MATCH_JALR, MASK_JALR, match_opcode, INSN_JSR},
 {"lb", 	0, INSN_CLASS_I, "d,o(s)", 	MATCH_LB, MASK_LB, match_opcode, INSN_DREF|INSN_1_BYTE},
 {"ld", 	64, INSN_CLASS_I, "d,o(s)", 	MATCH_LD, MASK_LD, match_opcode, INSN_DREF|INSN_8_BYTE},
 {"lh", 	0, INSN_CLASS_I, "d,o(s)", 	MATCH_LH, MASK_LH, match_opcode, INSN_DREF|INSN_2_BYTE},
 {"lr.b", 	0, INSN_CLASS_A, "d,0(s)", 	MATCH_LR_B, MASK_LR_B|MASK_AQRL, match_opcode, INSN_DREF|INSN_1_BYTE},
 {"lr.d", 	64, INSN_CLASS_A, "d,0(s)", 	MATCH_LR_D, MASK_LR_D|MASK_AQRL, match_opcode, INSN_DREF|INSN_8_BYTE},
 {"lr.h", 	0, INSN_CLASS_A, "d,0(s)", 	MATCH_LR_H, MASK_LR_H|MASK_AQRL, match_opcode, INSN_DREF|INSN_2_BYTE},
 {"lr.w", 	0, INSN_CLASS_A, "d,0(s)", 	MATCH_LR_W, MASK_LR_W|MASK_AQRL, match_opcode, INSN_DREF|INSN_4_BYTE},
 {"lui", 	0, INSN_CLASS_I, "d,u", 	MATCH_LUI, MASK_LUI, match_opcode, 0},
 {"lw", 	0, INSN_CLASS_I, "d,o(s)", 	MATCH_LW, MASK_LW, match_opcode, INSN_DREF|INSN_4_BYTE},
 {"max", 	0, INSN_CLASS_ZBB, "d,s,t", 	MATCH_MAX, MASK_MAX, match_opcode, 0},
 {"maxu", 	0, INSN_CLASS_ZBB, "d,s,t", 	MATCH_MAXU, MASK_MAXU, match_opcode, 0},
 {"min", 	0, INSN_CLASS_ZBB, "d,s,t", 	MATCH_MIN, MASK_MIN, match_opcode, 0},
 {"minu", 	0, INSN_CLASS_ZBB, "d,s,t", 	MATCH_MINU, MASK_MINU, match_opcode, 0},
 {"mret", 	0, INSN_CLASS_I, "", 	MATCH_MRET, MASK_MRET, match_opcode, 0},
 {"mul", 	0, INSN_CLASS_ZMMUL, "d,s,t", 	MATCH_MUL, MASK_MUL, match_opcode, 0},
 {"mulh", 	0, INSN_CLASS_ZMMUL, "d,s,t", 	MATCH_MULH, MASK_MULH, match_opcode, 0},
 {"mulhsu", 	0, INSN_CLASS_ZMMUL, "d,s,t", 	MATCH_MULHSU, MASK_MULHSU, match_opcode, 0},
 {"mulhu", 	0, INSN_CLASS_ZMMUL, "d,s,t", 	MATCH_MULHU, MASK_MULHU, match_opcode, 0},
 {"mulw", 	64, INSN_CLASS_ZMMUL, "d,s,t", 	MATCH_MULW, MASK_MULW, match_opcode, 0},
 {"or", 	0, INSN_CLASS_I, "d,s,t", 	MATCH_OR, MASK_OR, match_opcode, 0},
 {"orc.b", 	0, INSN_CLASS_ZBB, "d,s", MATCH_GORCI | MATCH_SHAMT_ORC_B, MASK_GORCI | MASK_SHAMT, match_opcode, 0},
 {"ori", 	0, INSN_CLASS_I, "d,s,j", 	MATCH_ORI, MASK_ORI, match_opcode, 0},
 {"orn", 	0, INSN_CLASS_ZBB_OR_ZBKB, "d,s,t", 	MATCH_ORN, MASK_ORN, match_opcode, 0},
 {"pack", 	0, INSN_CLASS_ZBKB, "d,s,t", 	MATCH_PACK, MASK_PACK, match_opcode, 0},
 {"packh", 	0, INSN_CLASS_ZBKB, "d,s,t", 	MATCH_PACKH, MASK_PACKH, match_opcode, 0},
 {"packw", 	64, INSN_CLASS_ZBKB, "d,s,t", 	MATCH_PACKW, MASK_PACKW, match_opcode, 0},
 {"rem", 	0, INSN_CLASS_M, "d,s,t", 	MATCH_REM, MASK_REM, match_opcode, 0},
 {"remu", 	0, INSN_CLASS_M, "d,s,t", 	MATCH_REMU, MASK_REMU, match_opcode, 0},
 {"remuw", 	64, INSN_CLASS_M, "d,s,t", 	MATCH_REMUW, MASK_REMUW, match_opcode, 0},
 {"remw", 	64, INSN_CLASS_M, "d,s,t", 	MATCH_REMW, MASK_REMW, match_opcode, 0},
 {"rev8", 	64, INSN_CLASS_ZBB_OR_ZBKB, "d,s", MATCH_GREVI | MATCH_SHAMT_REV8_64, MASK_GREVI | MASK_SHAMT, match_opcode, 0},
 {"rol", 	0, INSN_CLASS_ZBB_OR_ZBKB, "d,s,t", 	MATCH_ROL, MASK_ROL, match_opcode, 0},
 {"rolw", 	0, INSN_CLASS_ZBB_OR_ZBKB, "d,s,t", 	MATCH_ROLW, MASK_ROLW, match_opcode, 0},
 {"ror", 	0, INSN_CLASS_ZBB_OR_ZBKB, "d,s,t", 	MATCH_ROR, MASK_ROR, match_opcode, 0},
 {"rori", 	0, INSN_CLASS_ZBB_OR_ZBKB, "d,s,>", 	MATCH_RORI, MASK_RORI, match_opcode, 0},
 {"roriw", 	0, INSN_CLASS_ZBB_OR_ZBKB, "d,s,<", 	MATCH_RORIW, MASK_RORIW, match_opcode, 0},
 {"rorw", 	0, INSN_CLASS_ZBB_OR_ZBKB, "d,s,t", 	MATCH_RORW, MASK_RORW, match_opcode, 0},
 {"sb", 	0, INSN_CLASS_I, "t,q(s)", 	MATCH_SB, MASK_SB, match_opcode, INSN_DREF|INSN_1_BYTE},
 {"sc.b", 	0, INSN_CLASS_A, "d,t,0(s)", 	MATCH_SC_B, MASK_SC_B|MASK_AQRL, match_opcode, INSN_DREF|INSN_1_BYTE},
 {"sc.d", 	64, INSN_CLASS_A, "d,t,0(s)", 	MATCH_SC_D, MASK_SC_D|MASK_AQRL, match_opcode, INSN_DREF|INSN_8_BYTE},
 {"sc.h", 	0, INSN_CLASS_A, "d,t,0(s)", 	MATCH_SC_H, MASK_SC_H|MASK_AQRL, match_opcode, INSN_DREF|INSN_2_BYTE},
 {"sc.w", 	0, INSN_CLASS_A, "d,t,0(s)", 	MATCH_SC_W, MASK_SC_W|MASK_AQRL, match_opcode, INSN_DREF|INSN_4_BYTE},
 {"sd", 	64, INSN_CLASS_I, "t,q(s)", 	MATCH_SD, MASK_SD, match_opcode, INSN_DREF|INSN_8_BYTE},
 {"sext_b", 	0, INSN_CLASS_ZBB, "d,s", 	MATCH_SEXT_B, MASK_SEXT_B, match_opcode, 0},
 {"sext_h", 	0, INSN_CLASS_ZBB, "d,s", 	MATCH_SEXT_H, MASK_SEXT_H, match_opcode, 0},
 {"sfence_vma", 	0, INSN_CLASS_I, "s,t", 	MATCH_SFENCE_VMA, MASK_SFENCE_VMA, match_opcode, 0},
 {"sh", 	0, INSN_CLASS_I, "t,q(s)", 	MATCH_SH, MASK_SH, match_opcode, INSN_DREF|INSN_2_BYTE},
 {"sh1add", 	0, INSN_CLASS_I, "d,s,t", 	MATCH_SH1ADD, MASK_SH1ADD, match_opcode, 0},
 {"sh1add.uw", 	64, INSN_CLASS_ZBA, "d,s,t", 	MATCH_SH1ADD_UW, MASK_SH1ADD_UW, match_opcode, 0},
 {"sh2add", 	0, INSN_CLASS_I, "d,s,t", 	MATCH_SH2ADD, MASK_SH2ADD, match_opcode, 0},
 {"sh2add.uw", 	64, INSN_CLASS_ZBA, "d,s,t", 	MATCH_SH2ADD_UW, MASK_SH2ADD_UW, match_opcode, 0},
 {"sh3add", 	0, INSN_CLASS_I, "d,s,t", 	MATCH_SH3ADD, MASK_SH3ADD, match_opcode, 0},
 {"sh3add.uw", 	64, INSN_CLASS_ZBA, "d,s,t", 	MATCH_SH3ADD_UW, MASK_SH3ADD_UW, match_opcode, 0},
 {"sll", 	0, INSN_CLASS_I, "d,s,t", 	MATCH_SLL, MASK_SLL, match_opcode, 0},
 {"slli", 	0, INSN_CLASS_I, "d,s,>", 	MATCH_SLLI, MASK_SLLI, match_opcode, 0},
 {"slli.uw", 	64, INSN_CLASS_ZBA, "d,s,>", 	MATCH_SLLI_UW, MASK_SLLI_UW, match_opcode, 0},
 {"slliw", 	64, INSN_CLASS_I, "d,s,<", 	MATCH_SLLIW, MASK_SLLIW, match_opcode, 0},
 {"sllw", 	64, INSN_CLASS_I, "d,s,t", 	MATCH_SLLW, MASK_SLLW, match_opcode, 0},
 {"slt", 	0, INSN_CLASS_I, "d,s,t", 	MATCH_SLT, MASK_SLT, match_opcode, 0},
 {"slti", 	0, INSN_CLASS_I, "d,s,j", 	MATCH_SLTI, MASK_SLTI, match_opcode, 0},
 {"sltiu", 	0, INSN_CLASS_I, "d,s,j", 	MATCH_SLTIU, MASK_SLTIU, match_opcode, 0},
 {"sltu", 	0, INSN_CLASS_I, "d,s,t", 	MATCH_SLTU, MASK_SLTU, match_opcode, 0},
 {"sra", 	0, INSN_CLASS_I, "d,s,t", 	MATCH_SRA, MASK_SRA, match_opcode, 0},
 {"srai", 	0, INSN_CLASS_I, "d,s,>", 	MATCH_SRAI, MASK_SRAI, match_opcode, 0},
 {"sraiw", 	64, INSN_CLASS_I, "d,s,<", 	MATCH_SRAIW, MASK_SRAIW, match_opcode, 0},
 {"sraw", 	64, INSN_CLASS_I, "d,s,t", 	MATCH_SRAW, MASK_SRAW, match_opcode, 0},
 {"sret", 	0, INSN_CLASS_I, "", 	MATCH_SRET, MASK_SRET, match_opcode, 0},
 {"srl", 	0, INSN_CLASS_I, "d,s,t", 	MATCH_SRL, MASK_SRL, match_opcode, 0},
 {"srli", 	0, INSN_CLASS_I, "d,s,>", 	MATCH_SRLI, MASK_SRLI, match_opcode, 0},
 {"srliw", 	64, INSN_CLASS_I, "d,s,<", 	MATCH_SRLIW, MASK_SRLIW, match_opcode, 0},
 {"srlw", 	64, INSN_CLASS_I, "d,s,t", 	MATCH_SRLW, MASK_SRLW, match_opcode, 0},
 {"sub", 	0, INSN_CLASS_I, "d,s,t", 	MATCH_SUB, MASK_SUB, match_opcode, 0},
 {"subw", 	64, INSN_CLASS_I, "d,s,t", 	MATCH_SUBW, MASK_SUBW, match_opcode, 0},
 {"sw", 	0, INSN_CLASS_I, "t,q(s)", 	MATCH_SW, MASK_SW, match_opcode, INSN_DREF|INSN_4_BYTE},
 {"unzip", 	32, INSN_CLASS_ZBKB, "d,s", MATCH_UNSHFLI|MATCH_SHAMT_ZIP_32, MASK_UNSHFLI|MASK_SHAMT, match_opcode, 0},
 {"uret", 	0, INSN_CLASS_I, "", 	MATCH_URET, MASK_URET, match_opcode, 0},
 {"wfi", 	0, INSN_CLASS_I, "", 	MATCH_WFI, MASK_WFI, match_opcode, 0},
 {"xnor", 	0, INSN_CLASS_ZBB_OR_ZBKB, "d,s,t", 	MATCH_XNOR, MASK_XNOR, match_opcode, 0},
 {"xor", 	0, INSN_CLASS_I, "d,s,t", 	MATCH_XOR, MASK_XOR, match_opcode, 0},
 {"xori", 	0, INSN_CLASS_I, "d,s,j", 	MATCH_XORI, MASK_XORI, match_opcode, 0},
 {"xperm4", 	0, INSN_CLASS_ZBKX, "d,s,t", 	MATCH_XPERM4, MASK_XPERM4, match_opcode, 0},
 {"xperm8", 	0, INSN_CLASS_ZBKX, "d,s,t", 	MATCH_XPERM8, MASK_XPERM8, match_opcode, 0},
 {"zext_h", 	64, INSN_CLASS_ZBB, "d,s", 	MATCH_ZEXT_H, MASK_ZEXT_H|MASK_RS2, match_opcode, 0},
 {"zip", 	32, INSN_CLASS_ZBKB, "d,s", MATCH_SHFLI|MATCH_SHAMT_ZIP_32, MASK_SHFLI|MASK_SHAMT, match_opcode, 0},
 {"vaadd.vv", 	0, INSN_CLASS_V, "Vd,Vt,VsVm", 	MATCH_VAADD_VV, MASK_VAADD_VV, match_opcode, 0},
 {"vaadd.vx", 	0, INSN_CLASS_V, "Vd,Vt,sVm", 	MATCH_VAADD_VX, MASK_VAADD_VX, match_opcode, 0},
 {"vaaddu.vv", 	0, INSN_CLASS_V, "Vd,Vt,VsVm", 	MATCH_VAADDU_VV, MASK_VAADDU_VV, match_opcode, 0},
 {"vaaddu.vx", 	0, INSN_CLASS_V, "Vd,Vt,sVm", 	MATCH_VAADDU_VX, MASK_VAADDU_VX, match_opcode, 0},
 {"vadc.vim", 	0, INSN_CLASS_V, "Vd,Vt,Vi,V0", 	MATCH_VADC_VIM, MASK_VADC_VIM, match_opcode, 0},
 {"vadc.vvm", 	0, INSN_CLASS_V, "Vd,Vt,Vs,V0", 	MATCH_VADC_VVM, MASK_VADC_VVM, match_opcode, 0},
 {"vadc.vxm", 	0, INSN_CLASS_V, "Vd,Vt,s,V0", 	MATCH_VADC_VXM, MASK_VADC_VXM, match_opcode, 0},
 {"vadd.vi", 	0, INSN_CLASS_V, "Vd,Vt,ViVm", 	MATCH_VADD_VI, MASK_VADD_VI, match_opcode, 0},
 {"vadd.vv", 	0, INSN_CLASS_V, "Vd,Vt,VsVm", 	MATCH_VADD_VV, MASK_VADD_VV, match_opcode, 0},
 {"vadd.vx", 	0, INSN_CLASS_V, "Vd,Vt,sVm", 	MATCH_VADD_VX, MASK_VADD_VX, match_opcode, 0},
 {"vand.vi", 	0, INSN_CLASS_V, "Vd,Vt,ViVm", 	MATCH_VAND_VI, MASK_VAND_VI, match_opcode, 0},
 {"vand.vv", 	0, INSN_CLASS_V, "Vd,Vt,VsVm", 	MATCH_VAND_VV, MASK_VAND_VV, match_opcode, 0},
 {"vand.vx", 	0, INSN_CLASS_V, "Vd,Vt,sVm", 	MATCH_VAND_VX, MASK_VAND_VX, match_opcode, 0},
 {"vasub.vv", 	0, INSN_CLASS_V, "Vd,Vt,VsVm", 	MATCH_VASUB_VV, MASK_VASUB_VV, match_opcode, 0},
 {"vasub.vx", 	0, INSN_CLASS_V, "Vd,Vt,sVm", 	MATCH_VASUB_VX, MASK_VASUB_VX, match_opcode, 0},
 {"vasubu.vv", 	0, INSN_CLASS_V, "Vd,Vt,VsVm", 	MATCH_VASUBU_VV, MASK_VASUBU_VV, match_opcode, 0},
 {"vasubu.vx", 	0, INSN_CLASS_V, "Vd,Vt,sVm", 	MATCH_VASUBU_VX, MASK_VASUBU_VX, match_opcode, 0},
 {"vcompress.vm", 	0, INSN_CLASS_V, "Vd,Vt,Vs", 	MATCH_VCOMPRESS_VM, MASK_VCOMPRESS_VM, match_opcode, 0},
 {"vdiv.vv", 	0, INSN_CLASS_V, "Vd,Vt,VsVm", 	MATCH_VDIV_VV, MASK_VDIV_VV, match_opcode, 0},
 {"vdiv.vx", 	0, INSN_CLASS_V, "Vd,Vt,sVm", 	MATCH_VDIV_VX, MASK_VDIV_VX, match_opcode, 0},
 {"vdivu.vv", 	0, INSN_CLASS_V, "Vd,Vt,VsVm", 	MATCH_VDIVU_VV, MASK_VDIVU_VV, match_opcode, 0},
 {"vdivu.vx", 	0, INSN_CLASS_V, "Vd,Vt,sVm", 	MATCH_VDIVU_VX, MASK_VDIVU_VX, match_opcode, 0},
 {"vfadd.vf", 	0, INSN_CLASS_ZVEF, "Vd,Vt,sVm", 	MATCH_VFADD_VF, MASK_VFADD_VF, match_opcode, 0},
 {"vfadd.vv", 	0, INSN_CLASS_ZVEF, "Vd,Vt,VsVm", 	MATCH_VFADD_VV, MASK_VFADD_VV, match_opcode, 0},
 {"vfclass.v", 	0, INSN_CLASS_ZVEF, "Vd,VtVm", 	MATCH_VFCLASS_V, MASK_VFCLASS_V, match_opcode, 0},
 {"vfcvt.f.x.v", 	0, INSN_CLASS_ZVEF, "Vd,VtVm", 	MATCH_VFCVT_F_X_V, MASK_VFCVT_F_X_V, match_opcode, 0},
 {"vfcvt.f.xu.v", 	0, INSN_CLASS_ZVEF, "Vd,VtVm", 	MATCH_VFCVT_F_XU_V, MASK_VFCVT_F_XU_V, match_opcode, 0},
 {"vfcvt.rtz.x.f.v", 	0, INSN_CLASS_ZVEF, "Vd,VtVm", 	MATCH_VFCVT_RTZ_X_F_V, MASK_VFCVT_RTZ_X_F_V, match_opcode, 0},
 {"vfcvt.rtz.xu.f.v", 	0, INSN_CLASS_ZVEF, "Vd,VtVm", 	MATCH_VFCVT_RTZ_XU_F_V, MASK_VFCVT_RTZ_XU_F_V, match_opcode, 0},
 {"vfcvt.x.f.v", 	0, INSN_CLASS_ZVEF, "Vd,VtVm", 	MATCH_VFCVT_X_F_V, MASK_VFCVT_X_F_V, match_opcode, 0},
 {"vfcvt.xu.f.v", 	0, INSN_CLASS_ZVEF, "Vd,VtVm", 	MATCH_VFCVT_XU_F_V, MASK_VFCVT_XU_F_V, match_opcode, 0},
 {"vfdiv.vf", 	0, INSN_CLASS_ZVEF, "Vd,Vt,sVm", 	MATCH_VFDIV_VF, MASK_VFDIV_VF, match_opcode, 0},
 {"vfdiv.vv", 	0, INSN_CLASS_ZVEF, "Vd,Vt,VsVm", 	MATCH_VFDIV_VV, MASK_VFDIV_VV, match_opcode, 0},
 {"vfirst.m", 	0, INSN_CLASS_V, "d,VtVm", 	MATCH_VFIRST_M, MASK_VFIRST_M, match_opcode, 0},
 {"vfmacc.vf", 	0, INSN_CLASS_ZVEF, "Vd,s,VtVm", 	MATCH_VFMACC_VF, MASK_VFMACC_VF, match_opcode, 0},
 {"vfmacc.vv", 	0, INSN_CLASS_ZVEF, "Vd,Vs,VtVm", 	MATCH_VFMACC_VV, MASK_VFMACC_VV, match_opcode, 0},
 {"vfmadd.vf", 	0, INSN_CLASS_ZVEF, "Vd,s,VtVm", 	MATCH_VFMADD_VF, MASK_VFMADD_VF, match_opcode, 0},
 {"vfmadd.vv", 	0, INSN_CLASS_ZVEF, "Vd,Vs,VtVm", 	MATCH_VFMADD_VV, MASK_VFMADD_VV, match_opcode, 0},
 {"vfmax.vf", 	0, INSN_CLASS_ZVEF, "Vd,Vt,sVm", 	MATCH_VFMAX_VF, MASK_VFMAX_VF, match_opcode, 0},
 {"vfmax.vv", 	0, INSN_CLASS_ZVEF, "Vd,Vt,VsVm", 	MATCH_VFMAX_VV, MASK_VFMAX_VV, match_opcode, 0},
 {"vfmerge.vfm", 	0, INSN_CLASS_ZVEF, "Vd,Vt,S,V0", 	MATCH_VFMERGE_VFM, MASK_VFMERGE_VFM, match_opcode, 0},
 {"vfmin.vf", 	0, INSN_CLASS_ZVEF, "Vd,Vt,sVm", 	MATCH_VFMIN_VF, MASK_VFMIN_VF, match_opcode, 0},
 {"vfmin.vv", 	0, INSN_CLASS_ZVEF, "Vd,Vt,VsVm", 	MATCH_VFMIN_VV, MASK_VFMIN_VV, match_opcode, 0},
 {"vfmsac.vf", 	0, INSN_CLASS_ZVEF, "Vd,s,VtVm", 	MATCH_VFMSAC_VF, MASK_VFMSAC_VF, match_opcode, 0},
 {"vfmsac.vv", 	0, INSN_CLASS_ZVEF, "Vd,Vs,VtVm", 	MATCH_VFMSAC_VV, MASK_VFMSAC_VV, match_opcode, 0},
 {"vfmsub.vf", 	0, INSN_CLASS_ZVEF, "Vd,s,VtVm", 	MATCH_VFMSUB_VF, MASK_VFMSUB_VF, match_opcode, 0},
 {"vfmsub.vv", 	0, INSN_CLASS_ZVEF, "Vd,Vs,VtVm", 	MATCH_VFMSUB_VV, MASK_VFMSUB_VV, match_opcode, 0},
 {"vfmul.vf", 	0, INSN_CLASS_ZVEF, "Vd,Vt,sVm", 	MATCH_VFMUL_VF, MASK_VFMUL_VF, match_opcode, 0},
 {"vfmul.vv", 	0, INSN_CLASS_ZVEF, "Vd,Vt,VsVm", 	MATCH_VFMUL_VV, MASK_VFMUL_VV, match_opcode, 0},
 {"vfmv.f.s", 	0, INSN_CLASS_ZVEF, "D,Vt", 	MATCH_VFMV_F_S, MASK_VFMV_F_S, match_opcode, 0},
 {"vfmv.v.f", 	0, INSN_CLASS_ZVEF, "Vd,S", 	MATCH_VFMV_V_F, MASK_VFMV_V_F, match_opcode, 0},
 {"vfmvsf", 	0, INSN_CLASS_I, "Vd,S", 	MATCH_VFMVSF, MASK_VFMVSF, match_opcode, 0},
 {"vfncvt.f.f.w", 	0, INSN_CLASS_ZVEF, "Vd,VtVm", 	MATCH_VFNCVT_F_F_W, MASK_VFNCVT_F_F_W, match_opcode, 0},
 {"vfncvt.f.x.w", 	0, INSN_CLASS_ZVEF, "Vd,VtVm", 	MATCH_VFNCVT_F_X_W, MASK_VFNCVT_F_X_W, match_opcode, 0},
 {"vfncvt.f.xu.w", 	0, INSN_CLASS_ZVEF, "Vd,VtVm", 	MATCH_VFNCVT_F_XU_W, MASK_VFNCVT_F_XU_W, match_opcode, 0},
 {"vfncvt.rod.f.f.w", 	0, INSN_CLASS_ZVEF, "Vd,VtVm", 	MATCH_VFNCVT_ROD_F_F_W, MASK_VFNCVT_ROD_F_F_W, match_opcode, 0},
 {"vfncvt.rtz.x.f.w", 	0, INSN_CLASS_ZVEF, "Vd,VtVm", 	MATCH_VFNCVT_RTZ_X_F_W, MASK_VFNCVT_RTZ_X_F_W, match_opcode, 0},
 {"vfncvt.rtz.xu.f.w", 	0, INSN_CLASS_ZVEF, "Vd,VtVm", 	MATCH_VFNCVT_RTZ_XU_F_W, MASK_VFNCVT_RTZ_XU_F_W, match_opcode, 0},
 {"vfncvt.x.f.w", 	0, INSN_CLASS_ZVEF, "Vd,VtVm", 	MATCH_VFNCVT_X_F_W, MASK_VFNCVT_X_F_W, match_opcode, 0},
 {"vfncvt.xu.f.w", 	0, INSN_CLASS_ZVEF, "Vd,VtVm", 	MATCH_VFNCVT_XU_F_W, MASK_VFNCVT_XU_F_W, match_opcode, 0},
 {"vfnmacc.vf", 	0, INSN_CLASS_ZVEF, "Vd,s,VtVm", 	MATCH_VFNMACC_VF, MASK_VFNMACC_VF, match_opcode, 0},
 {"vfnmacc.vv", 	0, INSN_CLASS_ZVEF, "Vd,Vs,VtVm", 	MATCH_VFNMACC_VV, MASK_VFNMACC_VV, match_opcode, 0},
 {"vfnmadd.vf", 	0, INSN_CLASS_ZVEF, "Vd,s,VtVm", 	MATCH_VFNMADD_VF, MASK_VFNMADD_VF, match_opcode, 0},
 {"vfnmadd.vv", 	0, INSN_CLASS_ZVEF, "Vd,Vs,VtVm", 	MATCH_VFNMADD_VV, MASK_VFNMADD_VV, match_opcode, 0},
 {"vfnmsac.vf", 	0, INSN_CLASS_ZVEF, "Vd,s,VtVm", 	MATCH_VFNMSAC_VF, MASK_VFNMSAC_VF, match_opcode, 0},
 {"vfnmsac.vv", 	0, INSN_CLASS_ZVEF, "Vd,Vs,VtVm", 	MATCH_VFNMSAC_VV, MASK_VFNMSAC_VV, match_opcode, 0},
 {"vfnmsub.vf", 	0, INSN_CLASS_ZVEF, "Vd,s,VtVm", 	MATCH_VFNMSUB_VF, MASK_VFNMSUB_VF, match_opcode, 0},
 {"vfnmsub.vv", 	0, INSN_CLASS_ZVEF, "Vd,Vs,VtVm", 	MATCH_VFNMSUB_VV, MASK_VFNMSUB_VV, match_opcode, 0},
 {"vfrdiv.vf", 	0, INSN_CLASS_ZVEF, "Vd,Vt,sVm", 	MATCH_VFRDIV_VF, MASK_VFRDIV_VF, match_opcode, 0},
 {"vfrec7.v", 	0, INSN_CLASS_ZVEF, "Vd,VtVm", 	MATCH_VFREC7_V, MASK_VFREC7_V, match_opcode, 0},
 {"vfredmax.vs", 	0, INSN_CLASS_ZVEF, "Vd,Vt,VsVm", 	MATCH_VFREDMAX_VS, MASK_VFREDMAX_VS, match_opcode, 0},
 {"vfredmin.vs", 	0, INSN_CLASS_ZVEF, "Vd,Vt,VsVm", 	MATCH_VFREDMIN_VS, MASK_VFREDMIN_VS, match_opcode, 0},
 {"vfredosum.vs", 	0, INSN_CLASS_ZVEF, "Vd,Vt,VsVm", 	MATCH_VFREDOSUM_VS, MASK_VFREDOSUM_VS, match_opcode, 0},
 {"vfredusum.vs", 	0, INSN_CLASS_ZVEF, "Vd,Vt,VsVm", 	MATCH_VFREDUSUM_VS, MASK_VFREDUSUM_VS, match_opcode, 0},
 {"vfrsqrt7.v", 	0, INSN_CLASS_ZVEF, "Vd,VtVm", 	MATCH_VFRSQRT7_V, MASK_VFRSQRT7_V, match_opcode, 0},
 {"vfrsub.vf", 	0, INSN_CLASS_ZVEF, "Vd,Vt,sVm", 	MATCH_VFRSUB_VF, MASK_VFRSUB_VF, match_opcode, 0},
 {"vfsgnj.vf", 	0, INSN_CLASS_ZVEF, "Vd,Vt,sVm", 	MATCH_VFSGNJ_VF, MASK_VFSGNJ_VF, match_opcode, 0},
 {"vfsgnj.vv", 	0, INSN_CLASS_ZVEF, "Vd,Vt,VsVm", 	MATCH_VFSGNJ_VV, MASK_VFSGNJ_VV, match_opcode, 0},
 {"vfsgnjn.vf", 	0, INSN_CLASS_ZVEF, "Vd,Vt,sVm", 	MATCH_VFSGNJN_VF, MASK_VFSGNJN_VF, match_opcode, 0},
 {"vfsgnjn.vv", 	0, INSN_CLASS_ZVEF, "Vd,Vt,VsVm", 	MATCH_VFSGNJN_VV, MASK_VFSGNJN_VV, match_opcode, 0},
 {"vfsgnjx.vf", 	0, INSN_CLASS_ZVEF, "Vd,Vt,sVm", 	MATCH_VFSGNJX_VF, MASK_VFSGNJX_VF, match_opcode, 0},
 {"vfsgnjx.vv", 	0, INSN_CLASS_ZVEF, "Vd,Vt,VsVm", 	MATCH_VFSGNJX_VV, MASK_VFSGNJX_VV, match_opcode, 0},
 {"vfslide1down.vf", 	0, INSN_CLASS_ZVEF, "Vd,Vt,sVm", 	MATCH_VFSLIDE1DOWN_VF, MASK_VFSLIDE1DOWN_VF, match_opcode, 0},
 {"vfslide1up.vf", 	0, INSN_CLASS_ZVEF, "Vd,Vt,sVm", 	MATCH_VFSLIDE1UP_VF, MASK_VFSLIDE1UP_VF, match_opcode, 0},
 {"vfsqrt.v", 	0, INSN_CLASS_ZVEF, "Vd,VtVm", 	MATCH_VFSQRT_V, MASK_VFSQRT_V, match_opcode, 0},
 {"vfsub.vf", 	0, INSN_CLASS_ZVEF, "Vd,Vt,sVm", 	MATCH_VFSUB_VF, MASK_VFSUB_VF, match_opcode, 0},
 {"vfsub.vv", 	0, INSN_CLASS_ZVEF, "Vd,Vt,VsVm", 	MATCH_VFSUB_VV, MASK_VFSUB_VV, match_opcode, 0},
 {"vfwadd.vf", 	0, INSN_CLASS_ZVEF, "Vd,Vt,SVm", 	MATCH_VFWADD_VF, MASK_VFWADD_VF, match_opcode, 0},
 {"vfwadd.vv", 	0, INSN_CLASS_ZVEF, "Vd,Vt,VsVm", 	MATCH_VFWADD_VV, MASK_VFWADD_VV, match_opcode, 0},
 {"vfwadd.wf", 	0, INSN_CLASS_I, "Vd,Vt,SVm", 	MATCH_VFWADD_WF, MASK_VFWADD_WF, match_opcode, 0},
 {"vfwadd.wv", 	0, INSN_CLASS_ZVEF, "Vd,Vt,VsVm", 	MATCH_VFWADD_WV, MASK_VFWADD_WV, match_opcode, 0},
 {"vfwcvt.f.f.v", 	0, INSN_CLASS_ZVEF, "Vd,VtVm", 	MATCH_VFWCVT_F_F_V, MASK_VFWCVT_F_F_V, match_opcode, 0},
 {"vfwcvt.f.x.v", 	0, INSN_CLASS_ZVEF, "Vd,VtVm", 	MATCH_VFWCVT_F_X_V, MASK_VFWCVT_F_X_V, match_opcode, 0},
 {"vfwcvt.f.xu.v", 	0, INSN_CLASS_ZVEF, "Vd,VtVm", 	MATCH_VFWCVT_F_XU_V, MASK_VFWCVT_F_XU_V, match_opcode, 0},
 {"vfwcvt.rtz.x.f.v", 	0, INSN_CLASS_ZVEF, "Vd,VtVm", 	MATCH_VFWCVT_RTZ_X_F_V, MASK_VFWCVT_RTZ_X_F_V, match_opcode, 0},
 {"vfwcvt.rtz.xu.f.v", 	0, INSN_CLASS_ZVEF, "Vd,VtVm", 	MATCH_VFWCVT_RTZ_XU_F_V, MASK_VFWCVT_RTZ_XU_F_V, match_opcode, 0},
 {"vfwcvt.x.f.v", 	0, INSN_CLASS_ZVEF, "Vd,VtVm", 	MATCH_VFWCVT_X_F_V, MASK_VFWCVT_X_F_V, match_opcode, 0},
 {"vfwcvt.xu.f.v", 	0, INSN_CLASS_ZVEF, "Vd,VtVm", 	MATCH_VFWCVT_XU_F_V, MASK_VFWCVT_XU_F_V, match_opcode, 0},
 {"vfwmacc.vf", 	0, INSN_CLASS_ZVEF, "Vd,s,VtVm", 	MATCH_VFWMACC_VF, MASK_VFWMACC_VF, match_opcode, 0},
 {"vfwmacc.vv", 	0, INSN_CLASS_ZVEF, "Vd,Vs,VtVm", 	MATCH_VFWMACC_VV, MASK_VFWMACC_VV, match_opcode, 0},
 {"vfwmsac.vf", 	0, INSN_CLASS_ZVEF, "Vd,s,VtVm", 	MATCH_VFWMSAC_VF, MASK_VFWMSAC_VF, match_opcode, 0},
 {"vfwmsac.vv", 	0, INSN_CLASS_ZVEF, "Vd,Vs,VtVm", 	MATCH_VFWMSAC_VV, MASK_VFWMSAC_VV, match_opcode, 0},
 {"vfwmul.vf", 	0, INSN_CLASS_ZVEF, "Vd,Vt,SVm", 	MATCH_VFWMUL_VF, MASK_VFWMUL_VF, match_opcode, 0},
 {"vfwmul.vv", 	0, INSN_CLASS_ZVEF, "Vd,Vt,VsVm", 	MATCH_VFWMUL_VV, MASK_VFWMUL_VV, match_opcode, 0},
 {"vfwnmacc.vf", 	0, INSN_CLASS_ZVEF, "Vd,s,VtVm", 	MATCH_VFWNMACC_VF, MASK_VFWNMACC_VF, match_opcode, 0},
 {"vfwnmacc.vv", 	0, INSN_CLASS_ZVEF, "Vd,Vs,VtVm", 	MATCH_VFWNMACC_VV, MASK_VFWNMACC_VV, match_opcode, 0},
 {"vfwnmsac.vf", 	0, INSN_CLASS_ZVEF, "Vd,s,VtVm", 	MATCH_VFWNMSAC_VF, MASK_VFWNMSAC_VF, match_opcode, 0},
 {"vfwnmsac.vv", 	0, INSN_CLASS_ZVEF, "Vd,Vs,VtVm", 	MATCH_VFWNMSAC_VV, MASK_VFWNMSAC_VV, match_opcode, 0},
 {"vfwredosum.vs", 	0, INSN_CLASS_ZVEF, "Vd,Vt,VsVm", 	MATCH_VFWREDOSUM_VS, MASK_VFWREDOSUM_VS, match_opcode, 0},
 {"vfwredusum.vs", 	0, INSN_CLASS_ZVEF, "Vd,Vt,VsVm", 	MATCH_VFWREDUSUM_VS, MASK_VFWREDUSUM_VS, match_opcode, 0},
 {"vfwsub.vf", 	0, INSN_CLASS_ZVEF, "Vd,Vt,SVm", 	MATCH_VFWSUB_VF, MASK_VFWSUB_VF, match_opcode, 0},
 {"vfwsub.vv", 	0, INSN_CLASS_ZVEF, "Vd,Vt,VsVm", 	MATCH_VFWSUB_VV, MASK_VFWSUB_VV, match_opcode, 0},
 {"vfwsub.wf", 	0, INSN_CLASS_I, "Vd,Vt,SVm", 	MATCH_VFWSUB_WF, MASK_VFWSUB_WF, match_opcode, 0},
 {"vfwsub.wv", 	0, INSN_CLASS_ZVEF, "Vd,Vt,VsVm", 	MATCH_VFWSUB_WV, MASK_VFWSUB_WV, match_opcode, 0},
 {"vid.v", 	0, INSN_CLASS_V, "VdVm", 	MATCH_VID_V, MASK_VID_V, match_opcode, 0},
 {"viota.m", 	0, INSN_CLASS_V, "Vd,VtVm", 	MATCH_VIOTA_M, MASK_VIOTA_M, match_opcode, 0},
 {"vmacc.vv", 	0, INSN_CLASS_V, "Vd,Vs,VtVm", 	MATCH_VMACC_VV, MASK_VMACC_VV, match_opcode, 0},
 {"vmacc.vx", 	0, INSN_CLASS_V, "Vd,s,VtVm", 	MATCH_VMACC_VX, MASK_VMACC_VX, match_opcode, 0},
 {"vmadc.vi", 	0, INSN_CLASS_V, "Vd,Vt,Vi", 	MATCH_VMADC_VI, MASK_VMADC_VI, match_opcode, 0},
 {"vmadc.vim", 	0, INSN_CLASS_V, "Vd,Vt,Vi,V0", 	MATCH_VMADC_VIM, MASK_VMADC_VIM, match_opcode, 0},
 {"vmadc.vv", 	0, INSN_CLASS_V, "Vd,Vt,Vs", 	MATCH_VMADC_VV, MASK_VMADC_VV, match_opcode, 0},
 {"vmadc.vvm", 	0, INSN_CLASS_V, "Vd,Vt,Vs,V0", 	MATCH_VMADC_VVM, MASK_VMADC_VVM, match_opcode, 0},
 {"vmadc.vx", 	0, INSN_CLASS_V, "Vd,Vt,s", 	MATCH_VMADC_VX, MASK_VMADC_VX, match_opcode, 0},
 {"vmadc.vxm", 	0, INSN_CLASS_V, "Vd,Vt,s,V0", 	MATCH_VMADC_VXM, MASK_VMADC_VXM, match_opcode, 0},
 {"vmadd.vv", 	0, INSN_CLASS_V, "Vd,Vs,VtVm", 	MATCH_VMADD_VV, MASK_VMADD_VV, match_opcode, 0},
 {"vmadd.vx", 	0, INSN_CLASS_V, "Vd,s,VtVm", 	MATCH_VMADD_VX, MASK_VMADD_VX, match_opcode, 0},
 {"vmand.mm", 	0, INSN_CLASS_V, "Vd,Vt,Vs", 	MATCH_VMAND_MM, MASK_VMAND_MM, match_opcode, 0},
 {"vmandnot.mm", 	0, INSN_CLASS_V, "Vd,Vt,Vs", 	MATCH_VMANDNOT_MM, MASK_VMANDNOT_MM, match_opcode, 0},
 {"vmax.vv", 	0, INSN_CLASS_V, "Vd,Vt,VsVm", 	MATCH_VMAX_VV, MASK_VMAX_VV, match_opcode, 0},
 {"vmax.vx", 	0, INSN_CLASS_V, "Vd,Vt,sVm", 	MATCH_VMAX_VX, MASK_VMAX_VX, match_opcode, 0},
 {"vmaxu.vv", 	0, INSN_CLASS_V, "Vd,Vt,VsVm", 	MATCH_VMAXU_VV, MASK_VMAXU_VV, match_opcode, 0},
 {"vmaxu.vx", 	0, INSN_CLASS_V, "Vd,Vt,sVm", 	MATCH_VMAXU_VX, MASK_VMAXU_VX, match_opcode, 0},
 {"vmerge.vim", 	0, INSN_CLASS_I, "Vd,Vt,Vi,V0", 	MATCH_VMERGE_VIM, MASK_VMERGE_VIM, match_opcode, 0},
 {"vmerge.vvm", 	0, INSN_CLASS_I, "Vd,Vt,Vs,V0", 	MATCH_VMERGE_VVM, MASK_VMERGE_VVM, match_opcode, 0},
 {"vmerge.vxm", 	0, INSN_CLASS_V, "Vd,Vt,s,V0", 	MATCH_VMERGE_VXM, MASK_VMERGE_VXM, match_opcode, 0},
 {"vmfeq.vf", 	0, INSN_CLASS_ZVEF, "Vd,Vt,SVm", 	MATCH_VMFEQ_VF, MASK_VMFEQ_VF, match_opcode, 0},
 {"vmfeq.vv", 	0, INSN_CLASS_ZVEF, "Vd,Vt,VsVm", 	MATCH_VMFEQ_VV, MASK_VMFEQ_VV, match_opcode, 0},
 {"vmfge.vf", 	0, INSN_CLASS_ZVEF, "Vd,Vt,SVm", 	MATCH_VMFGE_VF, MASK_VMFGE_VF, match_opcode, 0},
 {"vmfgt.vf", 	0, INSN_CLASS_ZVEF, "Vd,Vt,SVm", 	MATCH_VMFGT_VF, MASK_VMFGT_VF, match_opcode, 0},
 {"vmfle.vf", 	0, INSN_CLASS_ZVEF, "Vd,Vt,SVm", 	MATCH_VMFLE_VF, MASK_VMFLE_VF, match_opcode, 0},
 {"vmfle.vv", 	0, INSN_CLASS_ZVEF, "Vd,Vt,VsVm", 	MATCH_VMFLE_VV, MASK_VMFLE_VV, match_opcode, 0},
 {"vmflt.vf", 	0, INSN_CLASS_ZVEF, "Vd,Vt,SVm", 	MATCH_VMFLT_VF, MASK_VMFLT_VF, match_opcode, 0},
 {"vmflt.vv", 	0, INSN_CLASS_ZVEF, "Vd,Vt,VsVm", 	MATCH_VMFLT_VV, MASK_VMFLT_VV, match_opcode, 0},
 {"vmfne.vf", 	0, INSN_CLASS_ZVEF, "Vd,Vt,SVm", 	MATCH_VMFNE_VF, MASK_VMFNE_VF, match_opcode, 0},
 {"vmfne.vv", 	0, INSN_CLASS_ZVEF, "Vd,Vt,VsVm", 	MATCH_VMFNE_VV, MASK_VMFNE_VV, match_opcode, 0},
 {"vmin.vv", 	0, INSN_CLASS_V, "Vd,Vt,VsVm", 	MATCH_VMIN_VV, MASK_VMIN_VV, match_opcode, 0},
 {"vmin.vx", 	0, INSN_CLASS_V, "Vd,Vt,sVm", 	MATCH_VMIN_VX, MASK_VMIN_VX, match_opcode, 0},
 {"vminu.vv", 	0, INSN_CLASS_V, "Vd,Vt,VsVm", 	MATCH_VMINU_VV, MASK_VMINU_VV, match_opcode, 0},
 {"vminu.vx", 	0, INSN_CLASS_V, "Vd,Vt,sVm", 	MATCH_VMINU_VX, MASK_VMINU_VX, match_opcode, 0},
 {"vmnand.mm", 	0, INSN_CLASS_V, "Vd,Vt,Vs", 	MATCH_VMNAND_MM, MASK_VMNAND_MM, match_opcode, 0},
 {"vmnor.mm", 	0, INSN_CLASS_V, "Vd,Vt,Vs", 	MATCH_VMNOR_MM, MASK_VMNOR_MM, match_opcode, 0},
 {"vmor.mm", 	0, INSN_CLASS_V, "Vd,Vt,Vs", 	MATCH_VMOR_MM, MASK_VMOR_MM, match_opcode, 0},
 {"vmornot.mm", 	0, INSN_CLASS_V, "Vd,Vt,Vs", 	MATCH_VMORNOT_MM, MASK_VMORNOT_MM, match_opcode, 0},
 {"vmsbc.vv", 	0, INSN_CLASS_V, "Vd,Vt,Vs", 	MATCH_VMSBC_VV, MASK_VMSBC_VV, match_opcode, 0},
 {"vmsbc.vvm", 	0, INSN_CLASS_V, "Vd,Vt,Vs,V0", 	MATCH_VMSBC_VVM, MASK_VMSBC_VVM, match_opcode, 0},
 {"vmsbc.vx", 	0, INSN_CLASS_V, "Vd,Vt,s", 	MATCH_VMSBC_VX, MASK_VMSBC_VX, match_opcode, 0},
 {"vmsbc.vxm", 	0, INSN_CLASS_V, "Vd,Vt,s,V0", 	MATCH_VMSBC_VXM, MASK_VMSBC_VXM, match_opcode, 0},
 {"vmsbf.m", 	0, INSN_CLASS_V, "Vd,VtVm", 	MATCH_VMSBF_M, MASK_VMSBF_M, match_opcode, 0},
 {"vmseq.vi", 	0, INSN_CLASS_V, "Vd,Vt,ViVm", 	MATCH_VMSEQ_VI, MASK_VMSEQ_VI, match_opcode, 0},
 {"vmseq.vv", 	0, INSN_CLASS_V, "Vd,Vt,VsVm", 	MATCH_VMSEQ_VV, MASK_VMSEQ_VV, match_opcode, 0},
 {"vmseq.vx", 	0, INSN_CLASS_V, "Vd,Vt,sVm", 	MATCH_VMSEQ_VX, MASK_VMSEQ_VX, match_opcode, 0},
 {"vmsgt.vi", 	0, INSN_CLASS_V, "Vd,Vt,ViVm", 	MATCH_VMSGT_VI, MASK_VMSGT_VI, match_opcode, 0},
 {"vmsgt.vx", 	0, INSN_CLASS_V, "Vd,Vt,sVm", 	MATCH_VMSGT_VX, MASK_VMSGT_VX, match_opcode, 0},
 {"vmsgtu.vi", 	0, INSN_CLASS_V, "Vd,Vt,ViVm", 	MATCH_VMSGTU_VI, MASK_VMSGTU_VI, match_opcode, 0},
 {"vmsgtu.vx", 	0, INSN_CLASS_V, "Vd,Vt,sVm", 	MATCH_VMSGTU_VX, MASK_VMSGTU_VX, match_opcode, 0},
 {"vmsif.m", 	0, INSN_CLASS_V, "Vd,VtVm", 	MATCH_VMSIF_M, MASK_VMSIF_M, match_opcode, 0},
 {"vmsle.vi", 	0, INSN_CLASS_V, "Vd,Vt,ViVm", 	MATCH_VMSLE_VI, MASK_VMSLE_VI, match_opcode, 0},
 {"vmsle.vv", 	0, INSN_CLASS_V, "Vd,Vt,VsVm", 	MATCH_VMSLE_VV, MASK_VMSLE_VV, match_opcode, 0},
 {"vmsle.vx", 	0, INSN_CLASS_V, "Vd,Vt,sVm", 	MATCH_VMSLE_VX, MASK_VMSLE_VX, match_opcode, 0},
 {"vmsleu.vi", 	0, INSN_CLASS_V, "Vd,Vt,ViVm", 	MATCH_VMSLEU_VI, MASK_VMSLEU_VI, match_opcode, 0},
 {"vmsleu.vv", 	0, INSN_CLASS_V, "Vd,Vt,VsVm", 	MATCH_VMSLEU_VV, MASK_VMSLEU_VV, match_opcode, 0},
 {"vmsleu.vx", 	0, INSN_CLASS_V, "Vd,Vt,sVm", 	MATCH_VMSLEU_VX, MASK_VMSLEU_VX, match_opcode, 0},
 {"vmslt.vv", 	0, INSN_CLASS_V, "Vd,Vt,VsVm", 	MATCH_VMSLT_VV, MASK_VMSLT_VV, match_opcode, 0},
 {"vmslt.vx", 	0, INSN_CLASS_V, "Vd,Vt,sVm", 	MATCH_VMSLT_VX, MASK_VMSLT_VX, match_opcode, 0},
 {"vmsltu.vv", 	0, INSN_CLASS_V, "Vd,Vt,VsVm", 	MATCH_VMSLTU_VV, MASK_VMSLTU_VV, match_opcode, 0},
 {"vmsltu.vx", 	0, INSN_CLASS_V, "Vd,Vt,sVm", 	MATCH_VMSLTU_VX, MASK_VMSLTU_VX, match_opcode, 0},
 {"vmsne.vi", 	0, INSN_CLASS_V, "Vd,Vt,ViVm", 	MATCH_VMSNE_VI, MASK_VMSNE_VI, match_opcode, 0},
 {"vmsne.vv", 	0, INSN_CLASS_V, "Vd,Vt,VsVm", 	MATCH_VMSNE_VV, MASK_VMSNE_VV, match_opcode, 0},
 {"vmsne.vx", 	0, INSN_CLASS_V, "Vd,Vt,sVm", 	MATCH_VMSNE_VX, MASK_VMSNE_VX, match_opcode, 0},
 {"vmsof.m", 	0, INSN_CLASS_V, "Vd,VtVm", 	MATCH_VMSOF_M, MASK_VMSOF_M, match_opcode, 0},
 {"vmul.vv", 	0, INSN_CLASS_V, "Vd,Vt,VsVm", 	MATCH_VMUL_VV, MASK_VMUL_VV, match_opcode, 0},
 {"vmul.vx", 	0, INSN_CLASS_V, "Vd,Vt,sVm", 	MATCH_VMUL_VX, MASK_VMUL_VX, match_opcode, 0},
 {"vmulh.vv", 	0, INSN_CLASS_V, "Vd,Vt,VsVm", 	MATCH_VMULH_VV, MASK_VMULH_VV, match_opcode, 0},
 {"vmulh.vx", 	0, INSN_CLASS_V, "Vd,Vt,sVm", 	MATCH_VMULH_VX, MASK_VMULH_VX, match_opcode, 0},
 {"vmulhsu.vv", 	0, INSN_CLASS_V, "Vd,Vt,VsVm", 	MATCH_VMULHSU_VV, MASK_VMULHSU_VV, match_opcode, 0},
 {"vmulhsu.vx", 	0, INSN_CLASS_V, "Vd,Vt,sVm", 	MATCH_VMULHSU_VX, MASK_VMULHSU_VX, match_opcode, 0},
 {"vmulhu.vv", 	0, INSN_CLASS_V, "Vd,Vt,VsVm", 	MATCH_VMULHU_VV, MASK_VMULHU_VV, match_opcode, 0},
 {"vmulhu.vx", 	0, INSN_CLASS_V, "Vd,Vt,sVm", 	MATCH_VMULHU_VX, MASK_VMULHU_VX, match_opcode, 0},
 {"vmv.s.x", 	0, INSN_CLASS_V, "Vd,s", 	MATCH_VMV_S_X, MASK_VMV_S_X, match_opcode, 0},
 {"vmv.v.i", 	0, INSN_CLASS_V, "Vd,Vi", 	MATCH_VMV_V_I, MASK_VMV_V_I, match_opcode, 0},
 {"vmv.v.v", 	0, INSN_CLASS_V, "Vd,Vs", 	MATCH_VMV_V_V, MASK_VMV_V_V, match_opcode, 0},
 {"vmv.v.x", 	0, INSN_CLASS_V, "Vd,s", 	MATCH_VMV_V_X, MASK_VMV_V_X, match_opcode, 0},
 {"vmv.x.s", 	0, INSN_CLASS_V, "d,Vt", 	MATCH_VMV_X_S, MASK_VMV_X_S, match_opcode, 0},
 {"vmv1r.v", 	0, INSN_CLASS_V, "Vi,Vd,Vt", 	MATCH_VMV1R_V, MASK_VMV1R_V, match_opcode, 0},
 {"vmv2r.v", 	0, INSN_CLASS_V, "Vi,Vd,Vt", 	MATCH_VMV2R_V, MASK_VMV2R_V, match_opcode, 0},
 {"vmv4r.v", 	0, INSN_CLASS_V, "Vi,Vd,Vt", 	MATCH_VMV4R_V, MASK_VMV4R_V, match_opcode, 0},
 {"vmv8r.v", 	0, INSN_CLASS_V, "Vi,Vd,Vt", 	MATCH_VMV8R_V, MASK_VMV8R_V, match_opcode, 0},
 {"vmxnor.mm", 	0, INSN_CLASS_V, "Vd,Vt,Vs", 	MATCH_VMXNOR_MM, MASK_VMXNOR_MM, match_opcode, 0},
 {"vmxor.mm", 	0, INSN_CLASS_V, "Vd,Vt,Vs", 	MATCH_VMXOR_MM, MASK_VMXOR_MM, match_opcode, 0},
 {"vnclip.wi", 	0, INSN_CLASS_V, "Vd,Vt,VjVm", 	MATCH_VNCLIP_WI, MASK_VNCLIP_WI, match_opcode, 0},
 {"vnclip.wv", 	0, INSN_CLASS_V, "Vd,Vt,VsVm", 	MATCH_VNCLIP_WV, MASK_VNCLIP_WV, match_opcode, 0},
 {"vnclip.wx", 	0, INSN_CLASS_V, "Vd,Vt,sVm", 	MATCH_VNCLIP_WX, MASK_VNCLIP_WX, match_opcode, 0},
 {"vnclipu.wi", 	0, INSN_CLASS_V, "Vd,Vt,VjVm", 	MATCH_VNCLIPU_WI, MASK_VNCLIPU_WI, match_opcode, 0},
 {"vnclipu.wv", 	0, INSN_CLASS_V, "Vd,Vt,VsVm", 	MATCH_VNCLIPU_WV, MASK_VNCLIPU_WV, match_opcode, 0},
 {"vnclipu.wx", 	0, INSN_CLASS_V, "Vd,Vt,sVm", 	MATCH_VNCLIPU_WX, MASK_VNCLIPU_WX, match_opcode, 0},
 {"vnmsac.vv", 	0, INSN_CLASS_V, "Vd,Vs,VtVm", 	MATCH_VNMSAC_VV, MASK_VNMSAC_VV, match_opcode, 0},
 {"vnmsac.vx", 	0, INSN_CLASS_V, "Vd,s,VtVm", 	MATCH_VNMSAC_VX, MASK_VNMSAC_VX, match_opcode, 0},
 {"vnmsub.vv", 	0, INSN_CLASS_V, "Vd,Vs,VtVm", 	MATCH_VNMSUB_VV, MASK_VNMSUB_VV, match_opcode, 0},
 {"vnmsub.vx", 	0, INSN_CLASS_V, "Vd,s,VtVm", 	MATCH_VNMSUB_VX, MASK_VNMSUB_VX, match_opcode, 0},
 {"vnsra.wi", 	0, INSN_CLASS_V, "Vd,Vt,VjVm", 	MATCH_VNSRA_WI, MASK_VNSRA_WI, match_opcode, 0},
 {"vnsra.wv", 	0, INSN_CLASS_V, "Vd,Vt,VsVm", 	MATCH_VNSRA_WV, MASK_VNSRA_WV, match_opcode, 0},
 {"vnsra.wx", 	0, INSN_CLASS_V, "Vd,Vt,sVm", 	MATCH_VNSRA_WX, MASK_VNSRA_WX, match_opcode, 0},
 {"vnsrl.wi", 	0, INSN_CLASS_V, "Vd,Vt,VjVm", 	MATCH_VNSRL_WI, MASK_VNSRL_WI, match_opcode, 0},
 {"vnsrl.wv", 	0, INSN_CLASS_V, "Vd,Vt,VsVm", 	MATCH_VNSRL_WV, MASK_VNSRL_WV, match_opcode, 0},
 {"vnsrl.wx", 	0, INSN_CLASS_V, "Vd,Vt,sVm", 	MATCH_VNSRL_WX, MASK_VNSRL_WX, match_opcode, 0},
 {"vor.vi", 	0, INSN_CLASS_V, "Vd,Vt,ViVm", 	MATCH_VOR_VI, MASK_VOR_VI, match_opcode, 0},
 {"vor.vv", 	0, INSN_CLASS_V, "Vd,Vt,VsVm", 	MATCH_VOR_VV, MASK_VOR_VV, match_opcode, 0},
 {"vor.vx", 	0, INSN_CLASS_V, "Vd,Vt,sVm", 	MATCH_VOR_VX, MASK_VOR_VX, match_opcode, 0},
 {"vpopc.m", 	0, INSN_CLASS_ZBB, "d,VtVm", 	MATCH_VPOPC_M, MASK_VPOPC_M, match_opcode, INSN_ALIAS},
 {"vredand.vs", 	0, INSN_CLASS_V, "Vd,Vt,VsVm", 	MATCH_VREDAND_VS, MASK_VREDAND_VS, match_opcode, 0},
 {"vredmax.vs", 	0, INSN_CLASS_V, "Vd,Vt,VsVm", 	MATCH_VREDMAX_VS, MASK_VREDMAX_VS, match_opcode, 0},
 {"vredmaxu.vs", 	0, INSN_CLASS_V, "Vd,Vt,VsVm", 	MATCH_VREDMAXU_VS, MASK_VREDMAXU_VS, match_opcode, 0},
 {"vredmin.vs", 	0, INSN_CLASS_V, "Vd,Vt,VsVm", 	MATCH_VREDMIN_VS, MASK_VREDMIN_VS, match_opcode, 0},
 {"vredminu.vs", 	0, INSN_CLASS_V, "Vd,Vt,VsVm", 	MATCH_VREDMINU_VS, MASK_VREDMINU_VS, match_opcode, 0},
 {"vredor.vs", 	0, INSN_CLASS_V, "Vd,Vt,VsVm", 	MATCH_VREDOR_VS, MASK_VREDOR_VS, match_opcode, 0},
 {"vredsum.vs", 	0, INSN_CLASS_V, "Vd,Vt,VsVm", 	MATCH_VREDSUM_VS, MASK_VREDSUM_VS, match_opcode, 0},
 {"vredxor.vs", 	0, INSN_CLASS_V, "Vd,Vt,VsVm", 	MATCH_VREDXOR_VS, MASK_VREDXOR_VS, match_opcode, 0},
 {"vrem.vs", 	0, INSN_CLASS_V, "Vd,Vt,VsVm", 	MATCH_VREM_VS, MASK_VREM_VS, match_opcode, 0},
 {"vrem.vx", 	0, INSN_CLASS_V, "Vd,Vt,sVm", 	MATCH_VREM_VX, MASK_VREM_VX, match_opcode, 0},
 {"vremu.vs", 	0, INSN_CLASS_V, "Vd,Vt,VsVm", 	MATCH_VREMU_VS, MASK_VREMU_VS, match_opcode, 0},
 {"vremu.vx", 	0, INSN_CLASS_V, "Vd,Vt,sVm", 	MATCH_VREMU_VX, MASK_VREMU_VX, match_opcode, 0},
 {"vrgather.vi", 	0, INSN_CLASS_V, "Vd,Vt,VjVm", 	MATCH_VRGATHER_VI, MASK_VRGATHER_VI, match_opcode, 0},
 {"vrgather.vv", 	0, INSN_CLASS_V, "Vd,Vt,VsVm", 	MATCH_VRGATHER_VV, MASK_VRGATHER_VV, match_opcode, 0},
 {"vrgather.vx", 	0, INSN_CLASS_V, "Vd,Vt,sVm", 	MATCH_VRGATHER_VX, MASK_VRGATHER_VX, match_opcode, 0},
 {"vrgatherei16.vv", 	0, INSN_CLASS_V, "Vd,Vt,VsVm", 	MATCH_VRGATHEREI16_VV, MASK_VRGATHEREI16_VV, match_opcode, 0},
 {"vrsub.vi", 	0, INSN_CLASS_V, "Vd,Vt,ViVm", 	MATCH_VRSUB_VI, MASK_VRSUB_VI, match_opcode, 0},
 {"vrsub.vx", 	0, INSN_CLASS_V, "Vd,Vt,sVm", 	MATCH_VRSUB_VX, MASK_VRSUB_VX, match_opcode, 0},
 {"vsadd.vi", 	0, INSN_CLASS_V, "Vd,Vt,ViVm", 	MATCH_VSADD_VI, MASK_VSADD_VI, match_opcode, 0},
 {"vsadd.vv", 	0, INSN_CLASS_V, "Vd,Vt,VsVm", 	MATCH_VSADD_VV, MASK_VSADD_VV, match_opcode, 0},
 {"vsadd.vx", 	0, INSN_CLASS_V, "Vd,Vt,sVm", 	MATCH_VSADD_VX, MASK_VSADD_VX, match_opcode, 0},
 {"vsaddu.vi", 	0, INSN_CLASS_V, "Vd,Vt,ViVm", 	MATCH_VSADDU_VI, MASK_VSADDU_VI, match_opcode, 0},
 {"vsaddu.vv", 	0, INSN_CLASS_V, "Vd,Vt,VsVm", 	MATCH_VSADDU_VV, MASK_VSADDU_VV, match_opcode, 0},
 {"vsaddu.vx", 	0, INSN_CLASS_V, "Vd,Vt,sVm", 	MATCH_VSADDU_VX, MASK_VSADDU_VX, match_opcode, 0},
 {"vsbc.vvm", 	0, INSN_CLASS_V, "Vd,Vt,Vs,V0", 	MATCH_VSBC_VVM, MASK_VSBC_VVM, match_opcode, 0},
 {"vsbc.vxm", 	0, INSN_CLASS_V, "Vd,Vt,s,V0", 	MATCH_VSBC_VXM, MASK_VSBC_VXM, match_opcode, 0},
 {"vsext.vf2", 	0, INSN_CLASS_V, "Vd,VtVm", 	MATCH_VSEXT_VF2, MASK_VSEXT_VF2, match_opcode, 0},
 {"vsext.vf4", 	0, INSN_CLASS_V, "Vd,VtVm", 	MATCH_VSEXT_VF4, MASK_VSEXT_VF4, match_opcode, 0},
 {"vsext.vf8", 	0, INSN_CLASS_V, "Vd,VtVm", 	MATCH_VSEXT_VF8, MASK_VSEXT_VF8, match_opcode, 0},
 {"vslide1down.vx", 	0, INSN_CLASS_V, "Vd,Vt,sVm", 	MATCH_VSLIDE1DOWN_VX, MASK_VSLIDE1DOWN_VX, match_opcode, 0},
 {"vslide1up.vx", 	0, INSN_CLASS_V, "Vd,Vt,sVm", 	MATCH_VSLIDE1UP_VX, MASK_VSLIDE1UP_VX, match_opcode, 0},
 {"vslidedown.vi", 	0, INSN_CLASS_V, "Vd,Vt,VjVm", 	MATCH_VSLIDEDOWN_VI, MASK_VSLIDEDOWN_VI, match_opcode, 0},
 {"vslidedown.vx", 	0, INSN_CLASS_V, "Vd,Vt,sVm", 	MATCH_VSLIDEDOWN_VX, MASK_VSLIDEDOWN_VX, match_opcode, 0},
 {"vslideup.vi", 	0, INSN_CLASS_V, "Vd,Vt,VjVm", 	MATCH_VSLIDEUP_VI, MASK_VSLIDEUP_VI, match_opcode, 0},
 {"vslideup.vx", 	0, INSN_CLASS_V, "Vd,Vt,sVm", 	MATCH_VSLIDEUP_VX, MASK_VSLIDEUP_VX, match_opcode, 0},
 {"vsll.vi", 	0, INSN_CLASS_V, "Vd,Vt,ViVm", 	MATCH_VSLL_VI, MASK_VSLL_VI, match_opcode, 0},
 {"vsll.vv", 	0, INSN_CLASS_V, "Vd,Vt,VsVm", 	MATCH_VSLL_VV, MASK_VSLL_VV, match_opcode, 0},
 {"vsll.vx", 	0, INSN_CLASS_V, "Vd,Vt,sVm", 	MATCH_VSLL_VX, MASK_VSLL_VX, match_opcode, 0},
 {"vsmul.vv", 	0, INSN_CLASS_V, "Vd,Vt,VsVm", 	MATCH_VSMUL_VV, MASK_VSMUL_VV, match_opcode, 0},
 {"vsmul.vx", 	0, INSN_CLASS_V, "Vd,Vt,sVm", 	MATCH_VSMUL_VX, MASK_VSMUL_VX, match_opcode, 0},
 {"vsra.vi", 	0, INSN_CLASS_V, "Vd,Vt,ViVm", 	MATCH_VSRA_VI, MASK_VSRA_VI, match_opcode, 0},
 {"vsra.vv", 	0, INSN_CLASS_V, "Vd,Vt,VsVm", 	MATCH_VSRA_VV, MASK_VSRA_VV, match_opcode, 0},
 {"vsra.vx", 	0, INSN_CLASS_V, "Vd,Vt,sVm", 	MATCH_VSRA_VX, MASK_VSRA_VX, match_opcode, 0},
 {"vsrl.vi", 	0, INSN_CLASS_V, "Vd,Vt,ViVm", 	MATCH_VSRL_VI, MASK_VSRL_VI, match_opcode, 0},
 {"vsrl.vv", 	0, INSN_CLASS_V, "Vd,Vt,VsVm", 	MATCH_VSRL_VV, MASK_VSRL_VV, match_opcode, 0},
 {"vsrl.vx", 	0, INSN_CLASS_V, "Vd,Vt,sVm", 	MATCH_VSRL_VX, MASK_VSRL_VX, match_opcode, 0},
 {"vssra.vi", 	0, INSN_CLASS_V, "Vd,Vt,ViVm", 	MATCH_VSSRA_VI, MASK_VSSRA_VI, match_opcode, 0},
 {"vssra.vv", 	0, INSN_CLASS_V, "Vd,Vt,VsVm", 	MATCH_VSSRA_VV, MASK_VSSRA_VV, match_opcode, 0},
 {"vssra.vx", 	0, INSN_CLASS_V, "Vd,Vt,sVm", 	MATCH_VSSRA_VX, MASK_VSSRA_VX, match_opcode, 0},
 {"vssrl.vi", 	0, INSN_CLASS_V, "Vd,Vt,ViVm", 	MATCH_VSSRL_VI, MASK_VSSRL_VI, match_opcode, 0},
 {"vssrl.vv", 	0, INSN_CLASS_V, "Vd,Vt,VsVm", 	MATCH_VSSRL_VV, MASK_VSSRL_VV, match_opcode, 0},
 {"vssrl.vx", 	0, INSN_CLASS_V, "Vd,Vt,sVm", 	MATCH_VSSRL_VX, MASK_VSSRL_VX, match_opcode, 0},
 {"vssub.vv", 	0, INSN_CLASS_V, "Vd,Vt,VsVm", 	MATCH_VSSUB_VV, MASK_VSSUB_VV, match_opcode, 0},
 {"vssub.vx", 	0, INSN_CLASS_V, "Vd,Vt,sVm", 	MATCH_VSSUB_VX, MASK_VSSUB_VX, match_opcode, 0},
 {"vssubu.vv", 	0, INSN_CLASS_V, "Vd,Vt,VsVm", 	MATCH_VSSUBU_VV, MASK_VSSUBU_VV, match_opcode, 0},
 {"vssubu.vx", 	0, INSN_CLASS_V, "Vd,Vt,sVm", 	MATCH_VSSUBU_VX, MASK_VSSUBU_VX, match_opcode, 0},
 {"vsub.vv", 	0, INSN_CLASS_V, "Vd,Vt,VsVm", 	MATCH_VSUB_VV, MASK_VSUB_VV, match_opcode, 0},
 {"vsub.vx", 	0, INSN_CLASS_V, "Vd,Vt,sVm", 	MATCH_VSUB_VX, MASK_VSUB_VX, match_opcode, 0},
 {"vwadd.vv", 	0, INSN_CLASS_V, "Vd,Vt,VsVm", 	MATCH_VWADD_VV, MASK_VWADD_VV, match_opcode, 0},
 {"vwadd.vx", 	0, INSN_CLASS_V, "Vd,Vt,sVm", 	MATCH_VWADD_VX, MASK_VWADD_VX, match_opcode, 0},
 {"vwadd.wv", 	0, INSN_CLASS_V, "Vd,Vt,VsVm", 	MATCH_VWADD_WV, MASK_VWADD_WV, match_opcode, 0},
 {"vwadd.wx", 	0, INSN_CLASS_V, "Vd,Vt,sVm", 	MATCH_VWADD_WX, MASK_VWADD_WX, match_opcode, 0},
 {"vwaddu.vv", 	0, INSN_CLASS_V, "Vd,Vt,VsVm", 	MATCH_VWADDU_VV, MASK_VWADDU_VV, match_opcode, 0},
 {"vwaddu.vx", 	0, INSN_CLASS_V, "Vd,Vt,sVm", 	MATCH_VWADDU_VX, MASK_VWADDU_VX, match_opcode, 0},
 {"vwaddu.wv", 	0, INSN_CLASS_V, "Vd,Vt,VsVm", 	MATCH_VWADDU_WV, MASK_VWADDU_WV, match_opcode, 0},
 {"vwaddu.wx", 	0, INSN_CLASS_V, "Vd,Vt,sVm", 	MATCH_VWADDU_WX, MASK_VWADDU_WX, match_opcode, 0},
 {"vwmacc.vv", 	0, INSN_CLASS_V, "Vd,Vs,VtVm", 	MATCH_VWMACC_VV, MASK_VWMACC_VV, match_opcode, 0},
 {"vwmacc.vx", 	0, INSN_CLASS_V, "Vd,s,VtVm", 	MATCH_VWMACC_VX, MASK_VWMACC_VX, match_opcode, 0},
 {"vwmaccsu.vv", 	0, INSN_CLASS_V, "Vd,Vs,VtVm", 	MATCH_VWMACCSU_VV, MASK_VWMACCSU_VV, match_opcode, 0},
 {"vwmaccsu.vx", 	0, INSN_CLASS_V, "Vd,s,VtVm", 	MATCH_VWMACCSU_VX, MASK_VWMACCSU_VX, match_opcode, 0},
 {"vwmaccu.vv", 	0, INSN_CLASS_V, "Vd,Vs,VtVm", 	MATCH_VWMACCU_VV, MASK_VWMACCU_VV, match_opcode, 0},
 {"vwmaccu.vx", 	0, INSN_CLASS_V, "Vd,s,VtVm", 	MATCH_VWMACCU_VX, MASK_VWMACCU_VX, match_opcode, 0},
 {"vwmaccus.vx", 	0, INSN_CLASS_V, "Vd,s,VtVm", 	MATCH_VWMACCUS_VX, MASK_VWMACCUS_VX, match_opcode, 0},
 {"vwmul.vv", 	0, INSN_CLASS_V, "Vd,Vt,VsVm", 	MATCH_VWMUL_VV, MASK_VWMUL_VV, match_opcode, 0},
 {"vwmul.vx", 	0, INSN_CLASS_V, "Vd,Vt,sVm", 	MATCH_VWMUL_VX, MASK_VWMUL_VX, match_opcode, 0},
 {"vwmulsu.vv", 	0, INSN_CLASS_V, "Vd,Vt,VsVm", 	MATCH_VWMULSU_VV, MASK_VWMULSU_VV, match_opcode, 0},
 {"vwmulsu.vx", 	0, INSN_CLASS_V, "Vd,Vt,sVm", 	MATCH_VWMULSU_VX, MASK_VWMULSU_VX, match_opcode, 0},
 {"vwmulu.vv", 	0, INSN_CLASS_V, "Vd,Vt,VsVm", 	MATCH_VWMULU_VV, MASK_VWMULU_VV, match_opcode, 0},
 {"vwmulu.vx", 	0, INSN_CLASS_V, "Vd,Vt,sVm", 	MATCH_VWMULU_VX, MASK_VWMULU_VX, match_opcode, 0},
 {"vwredsum.vs", 	0, INSN_CLASS_V, "Vd,Vt,VsVm", 	MATCH_VWREDSUM_VS, MASK_VWREDSUM_VS, match_opcode, 0},
 {"vwredsumu.vs", 	0, INSN_CLASS_V, "Vd,Vt,VsVm", 	MATCH_VWREDSUMU_VS, MASK_VWREDSUMU_VS, match_opcode, 0},
 {"vwsub.vv", 	0, INSN_CLASS_V, "Vd,Vt,VsVm", 	MATCH_VWSUB_VV, MASK_VWSUB_VV, match_opcode, 0},
 {"vwsub.vx", 	0, INSN_CLASS_V, "Vd,Vt,sVm", 	MATCH_VWSUB_VX, MASK_VWSUB_VX, match_opcode, 0},
 {"vwsub.wv", 	0, INSN_CLASS_V, "Vd,Vt,VsVm", 	MATCH_VWSUB_WV, MASK_VWSUB_WV, match_opcode, 0},
 {"vwsub.wx", 	0, INSN_CLASS_V, "Vd,Vt,sVm", 	MATCH_VWSUB_WX, MASK_VWSUB_WX, match_opcode, 0},
 {"vwsubu.vv", 	0, INSN_CLASS_V, "Vd,Vt,VsVm", 	MATCH_VWSUBU_VV, MASK_VWSUBU_VV, match_opcode, 0},
 {"vwsubu.vx", 	0, INSN_CLASS_V, "Vd,Vt,sVm", 	MATCH_VWSUBU_VX, MASK_VWSUBU_VX, match_opcode, 0},
 {"vwsubu.wv", 	0, INSN_CLASS_V, "Vd,Vt,VsVm", 	MATCH_VWSUBU_WV, MASK_VWSUBU_WV, match_opcode, 0},
 {"vwsubu.wx", 	0, INSN_CLASS_V, "Vd,Vt,sVm", 	MATCH_VWSUBU_WX, MASK_VWSUBU_WX, match_opcode, 0},
 {"vxor.vi", 	0, INSN_CLASS_V, "Vd,Vt,ViVm", 	MATCH_VXOR_VI, MASK_VXOR_VI, match_opcode, 0},
 {"vxor.vv", 	0, INSN_CLASS_V, "Vd,Vt,VsVm", 	MATCH_VXOR_VV, MASK_VXOR_VV, match_opcode, 0},
 {"vxor.vx", 	0, INSN_CLASS_V, "Vd,Vt,sVm", 	MATCH_VXOR_VX, MASK_VXOR_VX, match_opcode, 0},
 {"vzext.vf2", 	0, INSN_CLASS_V, "Vd,VtVm", 	MATCH_VZEXT_VF2, MASK_VZEXT_VF2, match_opcode, 0},
 {"vzext.vf4", 	0, INSN_CLASS_V, "Vd,VtVm", 	MATCH_VZEXT_VF4, MASK_VZEXT_VF4, match_opcode, 0},
 {"vzext.vf8", 	0, INSN_CLASS_V, "Vd,VtVm", 	MATCH_VZEXT_VF8, MASK_VZEXT_VF8, match_opcode, 0},
 /* Terminate the list.  */
{0, 0, INSN_CLASS_NONE, 0, 0, 0, 0, 0}
};

const struct riscv_opcode riscv_insn_types[] = 
{ 
/* Terminate the list.  */
{0, 0, INSN_CLASS_NONE, 0, 0, 0, 0, 0}
};
