const struct riscv_opcode riscv_opcodes[] =
{
{"fcvtmod.w.d", 	0, INSN_CLASS_D_AND_ZFA, "d,S", 	MATCH_FCVTMOD_W_D, MASK_FCVTMOD_W_D, match_opcode, 0},
 {"fleq.d", 	0, INSN_CLASS_D_AND_ZFA, "D,S,T", 	MATCH_FLEQ_D, MASK_FLEQ_D, match_opcode, 0},
 {"fleq.h", 	0, INSN_CLASS_ZFH_AND_ZFA, "D,S,T", 	MATCH_FLEQ_H, MASK_FLEQ_H, match_opcode, 0},
 {"fleq.s", 	0, INSN_CLASS_ZFA, "D,S,T", 	MATCH_FLEQ_S, MASK_FLEQ_S, match_opcode, 0},
 {"fli.d", 	0, INSN_CLASS_D_AND_ZFA, "D,Wfv", 	MATCH_FLI_D, MASK_FLI_D, match_opcode, 0},
 {"fli.h", 	0, INSN_CLASS_ZFH_OR_ZVFH_AND_ZFA, "D,Wfv", 	MATCH_FLI_H, MASK_FLI_H, match_opcode, 0},
 {"fli.s", 	0, INSN_CLASS_ZFA, "D,Wfv", 	MATCH_FLI_S, MASK_FLI_S, match_opcode, 0},
 {"fltq.d", 	0, INSN_CLASS_D_AND_ZFA, "D,S,T", 	MATCH_FLTQ_D, MASK_FLTQ_D, match_opcode, 0},
 {"fltq.h", 	0, INSN_CLASS_ZFH_AND_ZFA, "D,S,T", 	MATCH_FLTQ_H, MASK_FLTQ_H, match_opcode, 0},
 {"fltq.s", 	0, INSN_CLASS_ZFA, "D,S,T", 	MATCH_FLTQ_S, MASK_FLTQ_S, match_opcode, 0},
 {"fmaxm.d", 	0, INSN_CLASS_D_AND_ZFA, "D,S,T", 	MATCH_FMAXM_D, MASK_FMAXM_D, match_opcode, 0},
 {"fmaxm.h", 	0, INSN_CLASS_ZFH_AND_ZFA, "D,S,T", 	MATCH_FMAXM_H, MASK_FMAXM_H, match_opcode, 0},
 {"fmaxm.s", 	0, INSN_CLASS_ZFA, "D,S,T", 	MATCH_FMAXM_S, MASK_FMAXM_S, match_opcode, 0},
 {"fminm.d", 	0, INSN_CLASS_D_AND_ZFA, "D,S,T", 	MATCH_FMINM_D, MASK_FMINM_D, match_opcode, 0},
 {"fminm.h", 	0, INSN_CLASS_ZFH_AND_ZFA, "D,S,T", 	MATCH_FMINM_H, MASK_FMINM_H, match_opcode, 0},
 {"fminm.s", 	0, INSN_CLASS_ZFA, "D,S,T", 	MATCH_FMINM_S, MASK_FMINM_S, match_opcode, 0},
 {"fmvh.x.d", 	0, INSN_CLASS_D_AND_ZFA, "d,S", 	MATCH_FMVH_X_D, MASK_FMVH_X_D, match_opcode, 0},
 {"fmvp.d.x", 	0, INSN_CLASS_D_AND_ZFA, "D,s,t", 	MATCH_FMVP_D_X, MASK_FMVP_D_X, match_opcode, 0},
 {"fround.d", 	0, INSN_CLASS_D_AND_ZFA, "D,S", 	MATCH_FROUND_D|MASK_RM, MASK_FROUND_D|MASK_RM, match_opcode, 0},
 {"fround.h", 	0, INSN_CLASS_ZFH_AND_ZFA, "D,S", 	MATCH_FROUND_H|MASK_RM, MASK_FROUND_H|MASK_RM, match_opcode, 0},
 {"fround.s", 	0, INSN_CLASS_ZFA, "D,S", 	MATCH_FROUND_S|MASK_RM, MASK_FROUND_S|MASK_RM, match_opcode, 0},
 {"froundnx.d", 	0, INSN_CLASS_D_AND_ZFA, "D,S", 	MATCH_FROUNDNX_D|MASK_RM, MASK_FROUNDNX_D|MASK_RM, match_opcode, 0},
 {"froundnx.h", 	0, INSN_CLASS_ZFH_AND_ZFA, "D,S", 	MATCH_FROUNDNX_H|MASK_RM, MASK_FROUNDNX_H|MASK_RM, match_opcode, 0},
 {"froundnx.s", 	0, INSN_CLASS_ZFA, "D,S", 	MATCH_FROUNDNX_S|MASK_RM, MASK_FROUNDNX_S|MASK_RM, match_opcode, 0},
 